### PR TITLE
labeler: change nomerge to merge_option

### PR DESCRIPTION
**Pull request by disksing**
Signed-off-by: disksing <i@disksing.com>

### What problem does this PR solve?

Use region label `merge_option=deny` instead of `nomerge=true` to disallow region merge.

### What is changed and how it works?

- update label key and value
- update test

### Check List

Tests

- Unit test

### Release note

```release-note
None
```

### CODE REVIEW

**Review by JmPotato — APPROVED** [review]

**Review by rleungx — APPROVED** [review]

**Comment by disksing** [comment]
Please take another look. :( /cc @rleungx @JmPotato

**Review by rleungx — APPROVED** [review]

**Review by nolouch — APPROVED** [review]

**Pull request merged**
