### PR TITLE
metrics: keep region health same as before

### PR DESCRIPTION
**Pull request by rleungx**
### What problem does this PR solve?

PR #3035 use an individual gauge to record the offline related region health.

### What is changed and how it works?

This PR make the metrics look like the original one.

### Check List

Tests

- Manual test

### CODE REVIEW

**Review by disksing — APPROVED** [review]

**Comment by lhy1024** [comment]
what does this pr change?

**Comment by rleungx** [comment]
> what does this pr change?

Since PR #3035 use another gauge to record the offline related metrics, this PR is going to keep consistent with the original metrics

**Review by nolouch — APPROVED** [review]
lgtm

**Pull request merged**
