### PR TITLE
api: fix unstable test for TestSchedulerDiagnosticAPI

### LINKED ISSUE #5641: Unit test is not unstable

### PR DESCRIPTION
**Pull request by bufferflies**
Signed-off-by: bufferflies <1045931706@qq.com>

### What problem does this PR solve?
The balance region scheduler may not finished, so the result status needs to wait .

Issue Number: Close #5641

### What is changed and how does it work?

```commit-message
```

### Check List

Tests

Code changes

Side effects

Related changes

### Release note

```release-note
None.
```

### CODE REVIEW

**Review by lhy1024 — COMMENTED** [review]
There is still unstable test, https://github.com/tikv/pd/actions/runs/3335372899/jobs/5519276616

**Review by lhy1024 — APPROVED** [review]

**Comment by bufferflies** [comment]
> There is still unstable test, https://github.com/tikv/pd/actions/runs/3335372899/jobs/5519276616

fix all resutl status check

**Review by CabinfeverB — APPROVED** [review]

**Pull request merged**
