### PR TITLE
build: add `--always` to `git describe` (#3145)

### PR DESCRIPTION
**Pull request by ti-srebot**
cherry-pick #3145 to release-3.0

---

Signed-off-by: Zheng Xiangsheng <hundundm@gmail.com>

### What problem does this PR solve?

* In Travis CI, `fatal: No names found, cannot describe anything.` and `-ldflags '-X "github.com/tikv/pd/server/versioninfo.PDReleaseVersion="` can be described. 
* Example: https://travis-ci.org/github/tikv/pd/builds/741036669

### What is changed and how it works?

* build: add `--always` to `git describe`
* In the CI of this PR, `fatal: No names found, cannot describe anything.` will disappear.

### Check List

Related changes

- Need to cherry-pick to the release branch

### Release note

- No release note

### CODE REVIEW

**Comment by disksing** [comment]
@HunDunDM Please resolve conflicts

**Comment by HunDunDM** [comment]
@lhy1024 @disksing PTAL

**Review by lhy1024 — APPROVED** [review]

**Review by disksing — APPROVED** [review]

**Pull request merged**
