### PR TITLE
dashboard: update version

### LINKED ISSUE #6415: dashboard: support resource control panel

### PR DESCRIPTION
**Pull request by HuSharp**
### What problem does this PR solve?

Issue Number: Close #6415

### What is changed and how does it work?

```commit-message
dashboard: update version
```

### Check List

Tests

- Manual test (add detailed scripts or steps below)

### Release note

```release-note
None.
```

image

### CODE REVIEW

**Review by CabinfeverB — APPROVED** [review]

**Review by nolouch — APPROVED** [review]

**Comment by baurine** [comment]
This PR needs to be cherry-picked to release 6.5 branch, so it can be included in the 6.5.3 version, to fix https://github.com/pingcap/tidb-dashboard/issues/1515 issue for user.

**Comment by CabinfeverB** [comment]
> This PR needs to be cherry-picked to release 6.5 branch, so it can be included in the 6.5.3 version, to fix [pingcap/tidb-dashboard#1515](https://github.com/pingcap/tidb-dashboard/issues/1515) issue for user.
> 
> I found I can't add the cherry-pick label, anyone can help add the label? thanks! @nolouch @CabinfeverB

Why this PR needs to be cherry-picked to release 6.5? A new PR should be introduced to merge directly into 6.5

**Comment by baurine** [comment]
A new PR is fine as well, let's me try it.

**Comment by baurine** [comment]
new PR: https://github.com/tikv/pd/pull/6516

**Pull request merged**
