### PR TITLE
schedulers: return false if region bucket disable

### LINKED ISSUE #5051: scheduler: `split-bucket-scheduler`  will run if bucket is disbale.
## Bug Report
the config of `bucket-enable` is false, split bucket scheduler will scheduler. 

### What did you expect to see?
split bucket scheduler should be not allowed to scheduler
### What version of PD are you using (`pd-server -V`)?
master , 6.1.0

### PR DESCRIPTION
**Pull request by bufferflies**
Signed-off-by: bufferflies <1045931706@qq.com>

### What problem does this PR solve?

Issue Number: Close #5051

### What is changed and how does it work?

```commit-message
```

### Check List

Tests

Code changes

Side effects

Related changes

- Need to cherry-pick to the release branch

### Release note

```release-note
None.
```

### CODE REVIEW

**Comment by HunDunDM** [comment]
please fix test `testUnsafeRecoverySuite.TestRemoveFailedStores`

**Comment by bufferflies** [comment]
> please fix test `testUnsafeRecoverySuite.TestRemoveFailedStores`

fix

**Review by HunDunDM — APPROVED** [review]

**Review by rleungx — APPROVED** [review]

**Pull request merged**
