### PR TITLE
README: update the Go version from v1.19 to v1.20

### PR DESCRIPTION
**Pull request by Oreoxmt**
### What problem does this PR solve?

Issue Number: Close https://github.com/tikv/pd/issues/6499

### What is changed and how does it work?

```commit-message
* update the Go version from v1.19 to v1.20
```

### Check List

Tests

- No code

### Release note

```release-note
None.
```

### CODE REVIEW

**Review by rleungx — APPROVED** [review]

**Review by nolouch — APPROVED** [review]

**Comment by Oreoxmt** [comment]
> I'm waiting for a [tikv](https://github.com/orgs/tikv/people) member to verify that this patch is reasonable to test. If it is, they should reply with `/ok-to-test` on its own line. Until that is done, I will not automatically test new commits in this PR, but the usual testing commands by org member

@rleungx Please verify that this patch is reasonable to test (`/ok-to-test`)

**Pull request merged**
