### PR TITLE
scheduler: filter unhealthy store in summaryStoresLoad

### PR DESCRIPTION
**Pull request by lhy1024**
Signed-off-by: lhy1024 <admin@liudos.us>

### What problem does this PR solve?

Before this PR, we have not filtered unhealthy store in `summaryStoresLoad`, it will make exp to be inaccurate 

### What is changed and how it works?

Fix it

### Check List

Tests

- Unit test

### Release note

- Fix the issue that no filtered unhealthy store in `summaryStoresLoad`

### CODE REVIEW

**Comment by sunzhuohang** [comment]
LGTM

**Comment by Yisaer** [comment]
I think we can filter the unhealthy store in RaftCluster.`GetStoresStats` instead of inside `summaryStoresLoad` @lhy1024

**Comment by lhy1024** [comment]
> I think we can filter the unhealthy store in RaftCluster.`GetStoresStats` instead of inside `summaryStoresLoad` @lhy1024

I add check function before using `storestats` , PTAL @sunzhuohang @nolouch @Yisaer

**Review by Yisaer — APPROVED** [review]
LGTM

**Pull request merged**
