### PR TITLE
server: check the store version when changing tombstone status (#3200)

### PR DESCRIPTION
**Pull request by ti-srebot**
cherry-pick #3200 to release-4.0

---

Signed-off-by: Zheng Xiangsheng <hundundm@gmail.com>

### What problem does this PR solve?

* When changing a `Tombstone` store to `Up` or `Offline`, if the `cluster-version` has been upgraded at this time, the operation should fail.

### What is changed and how it works?

* The store of lower version is no longer allowed to change from `Tombstone` back to `Up`.
* Fix the bug that restarting the store will cause store-limit and statistics to be reset.

### Check List

Tests

- Unit test

Related changes

- Need to cherry-pick to the release branch

### Release note

- The store of lower version is no longer allowed to change from `Tombstone` back to `Up`.
- Fix the bug that restarting the store will cause store-limit and statistics to be reset.

### CODE REVIEW

**Comment by nolouch** [comment]
@HunDunDM, please resolve the conflict.

**Review by lhy1024 — APPROVED** [review]

**Review by nolouch — APPROVED** [review]

**Pull request merged**
