### PR TITLE
server: Auto fix gc_worker's service safepoint for upgraded clusters (#3371)

### LINKED ISSUE #3366: Service Safepoint with infinite TTL may keep disappearing after upgrading PD
## Bug Report

An extended problem of https://github.com/tikv/pd/issues/3128

### What did you do?

Upgrade from PD from v4.0.8 to v4.0.9.

### What did you expect to see?
PD should contain service_gc_safe_points `gc_worker` in PD etcd key.

Expected:
```
./pd-ctl service-gc-safepoint
{
  "service_gc_safe_points": [
    {
      "service_id": "gc_worker",
      "expired_at": 9223372036854775807,
      "safe_point": 422298434977136640
    }
    ...
}
```

### What did you see instead?

```
./pd-ctl service-gc-safepoint
{
  "service_gc_safe_points": [
    {
      "service_id": "ticdc",
      "expired_at": 1612125548,
      "safe_point": 422298434977136640
    }
  ],
  "gc_safe_point": 422141635726409728
}
```
service_id: "gc_worker" is still lost.

### What version of PD are you using (`pd-server -V`)?
```
Release Version: v4.0.9
Edition: Community
Git Commit Hash: 328752221729cca17b618fca75d161865e4da736
Git Branch: heads/refs/tags/v4.0.9
UTC Build Time:  2020-12-21 03:55:3
```

### PR DESCRIPTION
**Pull request by ti-srebot**
cherry-pick #3371 to release-4.0
You can switch your code base to this Pull Request by using [git-extras](https://github.com/tj/git-extras):
```bash
# In pd repo:
git pr https://github.com/tikv/pd/pull/3391
```

After apply modifications, you can push your change to this PR via:
```bash
git push git@github.com:ti-srebot/pd.git pr/3391:release-4.0-cbb89ec08597
```

---

Signed-off-by: MyonKeminta <MyonKeminta@users.noreply.github.com>

### What problem does this PR solve?

Fixes #3366

Though we did a fix in PR #3146 , there's still a problem for clusters upgraded from older version, where the gc_worker's service safepoint may be invalid or missing and there are other service safepoints in the cluster.

### What is changed and how it works?

Checks if "gc_worker"'s service safepoint exist and has a infinite TTL every time loading safepoints, and tries to fix it if possible.

### Check List

Tests

- Unit test

Code changes

- 

Side effects

- Increased code complexity

Related changes

- Need to cherry-pick to the release branch
  - release-4.0

### Release note

* No release note

### CODE REVIEW

**Comment by HunDunDM** [comment]
@MyonKeminta please fix the conflict.

**Review by nolouch — APPROVED** [review]
lgtm

**Review by Yisaer — APPROVED** [review]
LGTM

**Pull request merged**
