### PR TITLE
checker: update TTL according to SplitMergeInterval

### LINKED ISSUE #4614: split-merge-interval not work on empty regions generate before reset
### What did you do?
1、Set split-merge-interval  to 10h.
2、Drop some databases waiting for many empty regions generated..
3、Reset split-merge-interval to 10m
4、Wait more than 1 hours, no merge region operate created.

### What did you expect to see?
In step 4, empty regions should merge.

### What did you see instead?
In step 4, empty regions didn't merge.

### What version of PD are you using (`pd-server -V`)?
/var/lib/pd/log # /pd-ctl -V
Release Version: v5.5.0-nightly
Edition: Community
Git Commit Hash: 4f5a78a9014a5001844facaabf2586b99aa2ed44
Git Branch: heads/refs/tags/v5.5.0-nightly
UTC Build Time:  2022-01-23 06:10:1

### PR DESCRIPTION
**Pull request by rleungx**
Signed-off-by: Ryan Leung <rleungx@gmail.com>

### What problem does this PR solve?

Close #4614.

### What is changed and how it works?

Update TTL when split-merge-interval is changed.

### Check List

Tests

- Unit test

### Release note

```release-note
None
```

### CODE REVIEW

**Review by nolouch — APPROVED** [review]
lgtm

**Review by lhy1024 — COMMENTED** [review]
How about judging based on the configured time rather than using the fixed time?

**Review by JmPotato — APPROVED** [review]

**Review by lhy1024 — APPROVED** [review]

**Comment by lhy1024** [comment]
> How about judging based on the configured time rather than using the fixed time?

After discussion, it may be difficult to do GC.

**Pull request merged**
