### PR TITLE
*: enable more linters

### PR DESCRIPTION
**Pull request by rleungx**
Signed-off-by: Ryan Leung <rleungx@gmail.com>

### What problem does this PR solve?

Ref #4307.

### What is changed and how it works?

This PR enables the following linters:
- gocritic
- unparam
- unconvert
- whitespace
- makezero

### Check List

Tests

- Unit test

### Release note

```release-note
None
```

### CODE REVIEW

**Comment by disksing** [comment]
Please cc me after when it is ready for review.

**Review by JmPotato — APPROVED** [review]

**Comment by rleungx** [comment]
@disksing PTAL, thanks!

**Review by disksing — APPROVED** [review]

**Review by disksing — APPROVED** [review]

**Pull request merged**
