### PR TITLE
server: make TestRegionSynce stable

### PR DESCRIPTION
**Pull request by nolouch**
Signed-off-by: nolouch <nolouch@gmail.com>

### What problem does this PR solve?

ref #4348 

### Check List

Tests

- Unit test

### Release note

```release-note
None
```

### CODE REVIEW

**Comment by rleungx** [comment]
Seem it doesn't solve the problem.

**Comment by nolouch** [comment]
@rleungx Yep, I will test it in this PR first.

**Review by disksing — APPROVED** [review]

**Review by JmPotato — APPROVED** [review]

**Pull request merged**
