### PR TITLE
controller: Reduce the frequency of printing logs

### PR DESCRIPTION
**Pull request by nolouch**
### What problem does this PR solve?

Issue Number: Close https://github.com/tikv/pd/issues/8159

### What is changed and how does it work?

```commit-message
```

### Check List

Tests

- Unit test
- Integration test
- Manual test (add detailed scripts or steps below)

### Release note

```release-note
None.
```

### CODE REVIEW

**Review by disksing — APPROVED** [review]

**Review by rleungx — APPROVED** [review]

**Comment by lhy1024** [comment]
/cherry-pick-to-8.1

**Comment by lhy1024** [comment]
/needs-cherry-pick-8.1

**Pull request merged**
