### PR TITLE
schedule : fix the OpAdmin kind  should not occupy any limit  

### PR DESCRIPTION
**Pull request by bufferflies**
Signed-off-by: tongjian <1045931706@qq.com>
### What problem does this PR solve?

the OpAdmin Opkind operator should not occupy any limit 

### What is changed and how it works?
place OpAdmin first  
### Check List

Tests

- Unit test

Code changes

Side effects

Related changes
- Need to cherry-pick to the release branch

### Release note

```release-note
Please add a release note.

If you don't think this PR needs a release note then fill it with None.
```

### CODE REVIEW

**Review by HunDunDM — APPROVED** [review]

**Review by nolouch — APPROVED** [review]

**Comment by rleungx** [comment]
The release note needs to be changed. @bufferflies

**Comment by bufferflies** [comment]
fix admin bug: #3874

**Pull request merged**
