### PR TITLE
docs: update development doc

### PR DESCRIPTION
**Pull request by tisonkun**
### What problem does this PR solve?

straightforward typo fixes.

### Release note

```release-note
None
```

### CODE REVIEW

**Comment by JmPotato** [comment]
The `go.sum` change seems unnecessary. Could you please try to remove it？

**Comment by tisonkun** [comment]
> @tisonkun The `go.sum` change seems unnecessary. Could you please try to remove it？

ok make sense. But why when I execute `make` the `go.sum` file changed? Isn't it stable?

**Comment by tisonkun** [comment]
@JmPotato done. PTAL.

BTW codecov is quite noisy. I don't touch any line of code but coverage decreased.

**Comment by JmPotato** [comment]
> > @tisonkun The `go.sum` change seems unnecessary. Could you please try to remove it？
> 
> 
> 
> ok make sense. But why when I execute `make` the `go.sum` file changed? Isn't it stable?

I think it's caused by some static tools that `make` will use. I will take a look.

**Comment by JmPotato** [comment]
> @JmPotato done. PTAL.
> 
> 
> 
> BTW codecov is quite noisy. I don't touch any line of code but coverage decreased.

Yeah, it's basically not accurate at all… Maybe we can remove it some day.

**Pull request merged**
