### PR TITLE
ci: remove useless rebase

### PR DESCRIPTION
**Pull request by hi-rustin**
Signed-off-by: hi-rustin <rustin.liu@gmail.com>

### What problem does this PR solve?
https://github.com/tikv/pd/pull/3134#issuecomment-721533063
### What is changed and how it works?
Use author name.
### Check List

Tests

- No code

Code changes

None

Side effects

None
Related changes

None

### Release note

- No release note

### CODE REVIEW

**Review by lhy1024 — APPROVED** [review]

**Review by JmPotato — APPROVED** [review]

**Review by HunDunDM — APPROVED** [review]

**Comment by hi-rustin** [comment]
Still have some problems.

**Comment by hi-rustin** [comment]
Sorry I am idiot, `rebase` always change the hash.
I will find another way to fix it.

**Comment by hi-rustin** [comment]
@HunDunDM  @JmPotato  @lhy1024  

Now you can merge the master into your PR, if you use the `Update branch` button, the bot will keep the "status/can-merge" label.

**Review by HunDunDM — APPROVED** [review]

**Review by Yisaer — APPROVED** [review]
/lgtm

**Pull request merged**
