### PR TITLE
*: support generate the test coverage file and using it in ci

### PR DESCRIPTION
**Pull request by HuSharp**
### What problem does this PR solve?

Issue Number: Ref #7969

need merge https://github.com/ti-community-infra/configs/pull/1048/files firstly

### add coverprofile for pd-ut
```bash
$ ./bin/pd-ut run pkg/audit --coverprofile xxx
2024/03/27 17:37:18 maxprocs: Leaving GOMAXPROCS=8: CPU quota undefined
building task finish, parallelism=16, count=3, takes=2.976902167s
run all tasks takes 1.032669083s
```

```bash
support_coverprofile* $ cat xxx
mode: set
github.com/tikv/pd/pkg/audit/audit.go:44.58,45.37 1 1
github.com/tikv/pd/pkg/audit/audit.go:45.37,46.29 1 1
github.com/tikv/pd/pkg/audit/audit.go:46.29,48.4 1 1
github.com/tikv/pd/pkg/audit/audit.go:50.2,50.14 1 1
github.com/tikv/pd/pkg/audit/audit.go:59.48,61.2 1 0
github.com/tikv/pd/pkg/audit/audit.go:83.96,89.2 1 1
github.com/tikv/pd/pkg/audit/audit.go:92.81,94.9 2 1
github.com/tikv/pd/pkg/audit/audit.go:94.9,96.3 1 0
github.com/tikv/pd/pkg/audit/audit.go:97.2,98.9 2 1
github.com/tikv/pd/pkg/audit/audit.go:98.9,100.3 1 1
github.com/tikv/pd/pkg/audit/audit.go:101.2,102.13 2 1
github.com/tikv/pd/pkg/audit/audit.go:113.46,118.2 1 1
github.com/tikv/pd/pkg/audit/audit.go:121.68,123.9 2 1
github.com/tikv/pd/pkg/audit/audit.go:123.9,125.3 1 1
github.com/tikv/pd/pkg/audit/audit.go:126.2,127.13 2 1
```

```bash
support_coverprofile* $ go tool cover --func=xxx
github.com/tikv/pd/pkg/audit/audit.go:44:       Match                           100.0%
github.com/tikv/pd/pkg/audit/audit.go:59:       ProcessBeforeHandler            0.0%
github.com/tikv/pd/pkg/audit/audit.go:83:       NewPrometheusHistogramBackend   100.0%
github.com/tikv/pd/pkg/audit/audit.go:92:       ProcessHTTPRequest              87.5%
github.com/tikv/pd/pkg/audit/audit.go:113:      NewLocalLogBackend              100.0%
github.com/tikv/pd/pkg/audit/audit.go:121:      ProcessHTTPRequest              100.0%
total:                                          (statements)                    90.0%
```

### integrate ci unit tests job

advantage:
- now: run 2 chunks each 5min
- before: run 10 chunks each 5min

now
image

before 
image

```commit-message
```

### Check List

Tests

- Unit test
- Integration test
- Manual test (add detailed scripts or steps below)

### Release note

```release-note
None.
```

### CODE REVIEW

**Review by nolouch — APPROVED** [review]
lgtm

**Comment by HuSharp** [comment]
need to merge https://github.com/ti-community-infra/configs/pull/1048 firstly

**Comment by HuSharp** [comment]
/hold
wait for bot update

**Pull request merged**
