### PR TITLE
placement: do not delete orphan peers if some peers selected by RuleFit is down or pending (#4067)

### PR DESCRIPTION
**Pull request by andylokandy**
### What problem does this PR solve?

fixes https://github.com/tikv/pd/issues/4045

Related changes

- Need to cherry-pick to the release-5.0

### Release note

```release-note
None
```

### CODE REVIEW

**Review by disksing — APPROVED** [review]

**Comment by andylokandy** [comment]
@nolouch PTAL

**Review by nolouch — APPROVED** [review]

**Comment by nolouch** [comment]
Do we need to merge it?

**Comment by andylokandy** [comment]
@nolouch not yet. We may stay in this state until 15th October.

**Comment by rleungx** [comment]
@andylokandy Can we merge it now?

**Comment by andylokandy** [comment]
> @andylokandy Can we merge it now?

No. Instead please remove this branch, thanks.

**Pull request closed without merging**
