### PR TITLE
client/http: require source mark when initializing the http client

### PR DESCRIPTION
**Pull request by JmPotato**
### What problem does this PR solve?

Issue Number: ref #7300.

### What is changed and how does it work?

```commit-message
When creating a client, it is required to pass in the `source` parameter to further distinguish the source of logs and requests.
```

### Check List

Tests

- Unit test
- Integration test

### Release note

```release-note
None.
```

### CODE REVIEW

**Review by HuSharp — APPROVED** [review]
LGTM!

**Comment by JmPotato** [comment]
@CabinfeverB PTAL.

**Review by CabinfeverB — APPROVED** [review]

**Pull request merged**
