### PR TITLE
*: update actions 

### PR DESCRIPTION
**Pull request by dvrkps**
### What problem does this PR solve?

Issue Number: Ref #4399.

### What is changed and how does it work?
Update actions/setup-go, actions/checkout and actions/cache.

```commit-message
```

### Check List

Tests

- No code

### Release note

```release-note
None
```

### CODE REVIEW

**Comment by rleungx** [comment]
Please sign off DCO.

**Comment by dvrkps** [comment]
@rleungx done

**Review by bufferflies — APPROVED** [review]

**Review by JmPotato — APPROVED** [review]

**Review by rleungx — APPROVED** [review]

**Comment by rleungx** [comment]
@dvrkps Merged, thanks~

**Pull request merged**
