### PR TITLE
matrics: fold some panel

### PR DESCRIPTION
**Pull request by lhy1024**
Signed-off-by: lhy1024 <admin@liudos.us>

### What problem does this PR solve?

The status of operator, cluster and hot-write metrics panel is unfolded and the num of panels is zero.

image

### What is changed and how it works?

fold them

image

### Check List

Tests

- Unit test
- Manual test (add detailed scripts or steps below): import it and successful.

### Release note

- No release note

### CODE REVIEW

**Comment by rleungx** [comment]
https://github.com/pingcap/pd/pull/2518 does the same thing

**Comment by lhy1024** [comment]
> #2518 does the same thing

I think we can merge them separately to reduce the burden of review

**Review by rleungx — APPROVED** [review]
LGTM

**Pull request merged**
