### PR TITLE
change rule-group delete func to rule-bundle delete func

### LINKED ISSUE #5967: pd-ctl unable to delete rule-group
### What did you do?
- Add new placement rule group, ie `pd2`
- Execute `pd-ctl config placement-rules rule-group delete pd2`

### What did you expect to see?
Rule group `pd2` is removed

### What did you see instead?
Nothing changes, `pd-ctl config placement-rules show` shows `pd2` is still existed

### What version of PD are you using (`pd-server -V`)?
v6.1.1

### PR DESCRIPTION
**Pull request by matchge-ca**
### What problem does this PR solve?

Issue Number: Close #5967 

### What is changed and how does it work?

- Change `rule-group delete` func to `delRuleBundle`
- Add regex usage message in `rule-group delete` command desc
- Add deprecated message in `rule-group delete` command desc 

### Check List

Tests

- Manual test (add detailed scripts or steps below)
  - Compile & build pd-ctl
  - start a tiup playground, and added few placement rules
  - use `pd-ctl config placement-rules rule-group delete` command to delete one or some groups
  - check and validate the result

Code changes

Side effects

Related changes
- Need to cherry-pick to the release branch

### Release note

```release-note
None.
```

### CODE REVIEW

**Review by lhy1024 — APPROVED** [review]

**Review by lhy1024 — COMMENTED** [review]
maybe we also need to add a new unit test

**Review by bufferflies — APPROVED** [review]

**Comment by bufferflies** [comment]
CI failed

**Pull request closed without merging**
