### PR TITLE
checker: replace down check with disconnect check when fixing orphan peer(#7294)

### PR DESCRIPTION
**Pull request by lhy1024**
### What problem does this PR solve?

Issue Number: Close #7249

### What is changed and how does it work?

```commit-message
```

### Check List

Tests

- Unit test
- Integration test
- Manual test (add detailed scripts or steps below)
image

succesfully run test

image
no failure in tidb

image

all orphan peers are removed with 11min down store time config
### Release note

```release-note
None.
```

### CODE REVIEW

**Review by Connor1996 — APPROVED** [review]
LGTM

**Comment by lhy1024** [comment]
image

**Review by nolouch — APPROVED** [review]

**Pull request merged**
