### PR TITLE
test: increase test lease time to tolerate higher delayed time

### LINKED ISSUE #4442: `RaftCluster` panicked during the `TestMergeRegionOperator` test
## Bug Report

ref: https://ci2.pingcap.net/blue/organizations/jenkins/pd_test/detail/pd_test/4102/pipeline

```go
PANIC: operator_test.go:119: testOperatorSuite.TestMergeRegionOperator
[2021-12-08T14:24:06.451Z] 
[2021-12-08T14:24:06.451Z] ... Panic: runtime error: invalid memory address or nil pointer dereference (PC=0xA6BFF8)
[2021-12-08T14:24:06.451Z] 
[2021-12-08T14:24:06.451Z] /usr/local/go/src/runtime/panic.go:971
[2021-12-08T14:24:06.451Z]   in gopanic
[2021-12-08T14:24:06.451Z] /usr/local/go/src/runtime/panic.go:212
[2021-12-08T14:24:06.451Z]   in panicmem
[2021-12-08T14:24:06.451Z] /usr/local/go/src/runtime/signal_unix.go:734
[2021-12-08T14:24:06.451Z]   in sigpanic
[2021-12-08T14:24:06.451Z] /home/jenkins/agent/workspace/pd_test/go/src/github.com/pingcap/pd/server/cluster/cluster.go:635
[2021-12-08T14:24:06.451Z]   in RaftCluster.processRegionHeartbeat
[2021-12-08T14:24:06.451Z] /home/jenkins/agent/workspace/pd_test/go/src/github.com/pingcap/pd/server/cluster/cluster_worker.go:35
[2021-12-08T14:24:06.451Z]   in RaftCluster.HandleRegionHeartbeat
[2021-12-08T14:24:06.451Z] operator_test.go:401
[2021-12-08T14:24:06.451Z]   in mustRegionHeartbeat
[2021-12-08T14:24:06.451Z] operator_test.go:121
[2021-12-08T14:24:06.451Z]   in testOperatorSuite.TestMergeRegionOperator
[2021-12-08T14:24:06.451Z] /usr/local/go/src/reflect/value.go:337
[2021-12-08T14:24:06.451Z]   in Value.Call
[2021-12-08T14:24:06.451Z] /nfs/cache/mod/github.com/pingcap/check@v0.0.0-20200212061837-5e12011dc712/check.go:850
[2021-12-08T14:24:06.451Z]   in suiteRunner.forkTest.func1
[2021-12-08T14:24:06.451Z] /nfs/cache/mod/github.com/pingcap/check@v0.0.0-20200212061837-5e12011dc712/check.go:739
[2021-12-08T14:24:06.451Z]   in suiteRunner.forkCall.func1
[2021-12-08T14:24:06.451Z] /usr/local/go/src/runtime/asm_amd64.s:1371
[2021-12-08T14:24:06.451Z]   in goexit
```

### What version of PD are you using (`pd-server -V`)?

https://github.com/tikv/pd/pull/4441/commits/28d06c954e9ff57cd3cc1706cd43b2304140f72e

### PR DESCRIPTION
**Pull request by bufferflies**
Signed-off-by: bufferflies <1045931706@qq.com>

### What problem does this PR solve?
close #4442

### What is changed and how it works?
It set default  lease time to 10s(1s) for test and 3s for simulator  to keep consitence with develop.
### Check List

Tests

Code changes

Side effects

Related changes

### Release note

```release-note
None
```

### CODE REVIEW

**Review by JmPotato — APPROVED** [review]
LGTM

**Review by nolouch — APPROVED** [review]

**Comment by nolouch** [comment]
Does it works the lease time exceed election timeout？

**Comment by bufferflies** [comment]
> Does it works the lease time exceed election timeout？

The lease should write thought raft protocol, the new leader will has the lease info  if the etcd leader has changed during one lease time. I think it will work well.

**Pull request merged**
