### PR TITLE
dashboard: Update to TiDB Dashboard v2021.01.04.1 (#3326)

### PR DESCRIPTION
**Pull request by ti-srebot**
cherry-pick #3326 to release-4.0

---

Signed-off-by: Breezewish <me@breeswish.org>

### What problem does this PR solve?

Update to TiDB Dashboard v2021.01.04.1 to fix the bug that Statement is not working in TiDB 5.0 branch.

### What is changed and how it works?

Update to TiDB Dashboard v2021.01.04.1

### Check List

Tests

- Unit test
- Integration test

Related changes

- Need to cherry-pick to the release branch

### CODE REVIEW

**Comment by HunDunDM** [comment]
@breeswish please fix the conflict.

**Review by HunDunDM — APPROVED** [review]

**Review by breeswish — APPROVED** [review]

**Pull request merged**
