### PR TITLE
checker: check the target region size before doing merge operation (#3254)

### PR DESCRIPTION
**Pull request by ti-srebot**
cherry-pick #3254 to release-4.0

---

### What problem does this PR solve?

Closes https://github.com/tikv/pd/issues/3229

### What is changed and how it works?

This PR adds a check before doing the merge operation.

### Check List

Tests

- Unit test

### CODE REVIEW

**Review by JmPotato — APPROVED** [review]

**Review by lhy1024 — APPROVED** [review]

**Review by HunDunDM — APPROVED** [review]

**Comment by glorv** [comment]
lightning test is failed due to https://github.com/pingcap/tidb/pull/22359 this pr.

**Pull request merged**
