### PR TITLE
checker: priority to fix orphan peers 

### PR DESCRIPTION
**Pull request by nolouch**
### What problem does this PR solve?
ref https://github.com/tikv/pd/issues/3521
the problem is when offline a store, we may add learner multiple times if the operator is timeout.

### Check List

Tests

- Unit test
- Manual test (add detailed scripts or steps below)

Related changes

- PR to update [`pingcap/docs`](https://github.com/pingcap/docs)/[`pingcap/docs-cn`](https://github.com/pingcap/docs-cn):
- PR to update [`pingcap/tidb-ansible`](https://github.com/pingcap/tidb-ansible):
- Need to cherry-pick to the release branch

### CODE REVIEW

**Review by lhy1024 — APPROVED** [review]

**Comment by disksing** [comment]
need any test?

**Comment by disksing** [comment]
basically LGTM except for lack of tests.

**Comment by nolouch** [comment]
PTAL @disksing @HunDunDM

**Review by HunDunDM — APPROVED** [review]

**Pull request merged**
