### PR TITLE
dashboard: update to v6.6.0.1

### LINKED ISSUE #5962: Upgrade tidb dashboard to fix issue1478
## Development Task

See:  https://github.com/pingcap/tidb-dashboard/pull/1478

### PR DESCRIPTION
**Pull request by mornyx**
Signed-off-by: mornyx <mornyx.z@gmail.com>

### What problem does this PR solve?

Issue Number: Close #5962

### What is changed and how does it work?

Changes on TiDB dashboard: https://github.com/pingcap/tidb-dashboard/pull/1479

```commit-message
dashboard: update to v6.6.0.1
```

### Release note

```release-note
None
```

### CODE REVIEW

**Review by Yisaer — APPROVED** [review]

**Review by disksing — APPROVED** [review]

**Comment by nolouch** [comment]
@mornyx  need to run `make tidy`

**Comment by mornyx** [comment]
This PR is no longer needed as the issue is not caused by TiDB dashboard and I will close it, thanks all.

**Pull request closed without merging**
