### PR TITLE
statistics: refacter store load in hot region scheduler

### PR DESCRIPTION
**Pull request by rleungx**
### What problem does this PR solve?

Move store-related statistics for scheduler package to statistics package.

### What is changed and how it works?

- move the store load statistics from `util.go` to `store_load.go`

### Check List

Tests

- Unit test

### Release note

```release-note
None
```

### CODE REVIEW

**Comment by nolouch** [comment]
cc @lhy1024

**Comment by rleungx** [comment]
@lhy1024 PTAL

**Review by lhy1024 — APPROVED** [review]

**Review by bufferflies — APPROVED** [review]
lgtm

**Pull request merged**
