### PR TITLE
*: use errcode-gen in new location

### PR DESCRIPTION
**Pull request by AstroProfundis**
### What is changed and how it works?
Use new location of `errdoc-gen`.

### Check List

Tests

- Manual test (add detailed scripts or steps below)

Related changes

- https://github.com/pingcap/errors/pull/32
- Need to cherry-pick to the release branch

### CODE REVIEW

**Review by lonng — COMMENTED** [review]
LGTM

**Comment by rleungx** [comment]
CI failed. @AstroProfundis

**Review by disksing — APPROVED** [review]

**Comment by disksing** [comment]
Does it need to cherry-pick to release4.0?

**Comment by AstroProfundis** [comment]
> Does it need to cherry-pick to release4.0?

Yes, we want to remove the dependency of tiup as much as possible

**Review by rleungx — APPROVED** [review]

**Pull request merged**
