### PR TITLE
scheduler: simplify the limit judgment of hot-region-scheduler

### PR DESCRIPTION
**Pull request by HunDunDM**
Signed-off-by: HunDunDM <hundundm@gmail.com>

### What problem does this PR solve?

related #3778 
changes caused by #3820

### What is changed and how it works?

`OpLeader` and `LeaderScheduleLimit` are no longer judged in `balance-hot-region-scheduler`.

### Check List

Tests

- Unit test

Code changes

Side effects

Related changes

- Need to cherry-pick to the release branch

### Release note

```release-note
None
```

### CODE REVIEW

**Comment by bufferflies** [comment]
lgtm

**Review by nolouch — APPROVED** [review]
lgtm

**Comment by nolouch** [comment]
cc @lhy1024

**Review by lhy1024 — APPROVED** [review]

**Pull request merged**
