### PR TITLE
metrics: replace histogram with gauge in patrol region

### PR DESCRIPTION
**Pull request by rleungx**
### What problem does this PR solve?

We only need to record the latest time spent on patrol regions. No need to use histogram.

### What is changed and how it works?

This PR replaces histogram with gauge in patrol region.

### Check List

Tests

- Unit test

### CODE REVIEW

**Review by nolouch — COMMENTED** [review]
LGTM

**Comment by lhy1024** [comment]
why to replace it with gauge?

**Comment by rleungx** [comment]
> why to replace it with gauge?

We only need to record the time spent on the latest round.

**Review by HunDunDM — APPROVED** [review]
/lgtm

**Review by HunDunDM — APPROVED** [review]
/lgtm

**Review by HunDunDM — APPROVED** [review]

**Review by lhy1024 — APPROVED** [review]

**Comment by disksing** [comment]
should we choose another metrics name?

**Comment by rleungx** [comment]
> should we choose another metrics name?

Any suggestion?

**Comment by disksing** [comment]
> > should we choose another metrics name?
> 
> Any suggestion?

I don't know. I wonder if it will cause any problem when prometheus has stored data with same metrics name but different type.

**Comment by rleungx** [comment]
PTAL @disksing

**Review by disksing — APPROVED** [review]

**Pull request merged**
