### PR TITLE
*: rename the package name of test

### PR DESCRIPTION
**Pull request by rleungx**
### What problem does this PR solve?

Some test package names are not meet the standard of golang.

### What is changed and how it works?

This PR renames them and remove an unnecessary test also.

### Check List

Tests

- Unit test

### CODE REVIEW

**Comment by disksing** [comment]
why do they not meet standard?

**Comment by rleungx** [comment]
> why do they not meet standard?

See https://blog.golang.org/package-names

**Comment by disksing** [comment]
I think the document does not cover test packages. Actually, use `foo_test` is commonly used. You can find many usages in https://github.com/golang/go

**Comment by rleungx** [comment]
> I think the document does not cover test packages. Actually, `foo_test` style is very commonly used. You can find many usages in https://github.com/golang/go

Make sense. Shall we change other test package to foo_test?

**Comment by disksing** [comment]
Both ways are good, depends on if we want to do black box test or white box test.

**Review by lhy1024 — APPROVED** [review]

**Pull request closed without merging**
