### PR TITLE
*: move `tso` to `pkg`

### PR DESCRIPTION
**Pull request by rleungx**
Signed-off-by: Ryan Leung <rleungx@gmail.com>

### What problem does this PR solve?

Issue Number: Ref #5836.

### What is changed and how does it work?

```commit-message
```

### Check List

Tests

- Unit test

### Release note

```release-note
None
```

### CODE REVIEW

**Review by lhy1024 — APPROVED** [review]

**Review by JmPotato — APPROVED** [review]

**Review by binshi-bing — APPROVED** [review]
LGTM

**Review by binshi-bing — COMMENTED** [review]
shall we move server/tso/* to pkg/mcs/tso/? @rleungx @JmPotato

**Comment by rleungx** [comment]
> shall we move server/tso/* to pkg/mcs/tso/? just confirm. Moving to pkg/tso makes sense to me too, as it is the library shared by tso in all-in-one pd and tso microservice, and we put tso microservice specific code in pkg/mc/tso. @rleungx @JmPotato

IMO, the tso microservice related code should be put into `pkg/mcs/tso`, the common logic should be put into `/pkg`.

**Pull request merged**
