### PR TITLE
placement: do not delete orphan peers if some peers selected by RuleFit is down or pending

### PR DESCRIPTION
**Pull request by andylokandy**
### What problem does this PR solve?

fixes https://github.com/tikv/pd/issues/4045

Related changes

- Need to cherry-pick to the release-5.0

### Release note

```release-note
None
```

### CODE REVIEW

**Comment by disksing** [comment]
If pending peer is considered *not satisfied*, the checker will create an operator to replace the pending peer immediately. But I think in most cases, we should wait for the status to become normal rather than replace it.

**Comment by andylokandy** [comment]
@disksing I've reimplemented the patch, PTAL.

**Review by disksing — APPROVED** [review]

**Comment by disksing** [comment]
btw, can we add a test case for it?

**Review by nolouch — COMMENTED** [review]
could you add a test?

**Review by nolouch — APPROVED** [review]
lgtm

**Pull request merged**
