### PR TITLE
Bugfix when restarting from an existing cluster.

### LINKED ISSUE #6981: pd scheduler do not resume after lightning finished when rolling restarting pd during lightning importing
### What did you do?
1、lightning importing
2、rolling restart pd

### What did you expect to see?
pd scheduler can resume after lightning finished

### What did you see instead?
pd scheduler do not resume after lightning finished
image

image

### What version of PD are you using (`pd-server -V`)?
./pd-server -V
 Release Version: v7.4.0-alpha
Edition: Community
Git Commit Hash: 497c9420668e2a94f341f0c1d360d01058f99393
Git Branch: heads/refs/tags/v7.4.0-alpha
UTC Build Time:  2023-08-22 11:36:19
2023-08-23T14:59:33.891+0800    INFO    k8s/client.go:132       it should be noted that a long-running command will not be
interrupted even the use case has ended. For more information, please refer to https://github.com/pingcap/test-infra/discus
sions/129

### PR DESCRIPTION
**Pull request by LykxSassinator**
### What problem does this PR solve?

Issue Number: Close #6981 

### What is changed and how does it work?

```commit-message
Fix the bug when restarting from an existed cluster and schedulers will not resume.
```

### Check List

Tests

- Manual test (add detailed scripts or steps below)
img_v2_362ae1ee-6cef-450c-841f-2a8e180fe96g

Code changes

- Has the configuration change
- Has HTTP API interfaces changed (Don't forget to [add the declarative for the new API](https://github.com/tikv/pd/blob/master/docs/development.md#updating-api-documentation))
- Has persistent data change

Side effects

- Possible performance regression
- Increased code complexity
- Breaking backward compatibility

Related changes

- PR to update [`pingcap/docs`](https://github.com/pingcap/docs)/[`pingcap/docs-cn`](https://github.com/pingcap/docs-cn):
- PR to update [`pingcap/tiup`](https://github.com/pingcap/tiup):
- Need to cherry-pick to the release branch

### Release note

```release-note
None.
```

### CODE REVIEW

**Comment by LykxSassinator** [comment]
/assign @CabinfeverB 

PTAL, thx.

**Review by CabinfeverB — APPROVED** [review]

**Review by nolouch — APPROVED** [review]

**Review by lhy1024 — COMMENTED** [review]
Do we need to add a test to avoid a similiar problem?

**Comment by LykxSassinator** [comment]
> Do we need to add a test to avoid a similiar problem?

Nope, it's hard to add a ut for this case

**Pull request merged**
