### PR TITLE
[DNM] Test Bench

### PR DESCRIPTION
**Pull request by lhy1024**

### CODE REVIEW

**Comment by zz-jason** [comment]
how to read the benchmark result?

**Comment by lhy1024** [comment]
> how to read the benchmark result?

@zz-jason 
it will display some metrics that master branch and this pr branch, in this case, we hope that `balance_region_operator_count` and `balance_leader_operator_count` is less, it means that create less operator when scale out.

**Comment by lhy1024** [comment]
> /bench simulator

Do we need to go to compatible format？

**Comment by ZenoTan** [comment]
> > /bench simulator
> 
> Do we need to go to compatible format？

Yes. I will fix the format later.

**Comment by nolouch** [comment]
What the meaning of `Send Maximum`,`Send Minimum`?

**Comment by ZenoTan** [comment]
`Send Maximum` is is maximum snapshots send in all stores. Refer to `statistics.go` in simulator.

**Pull request closed without merging**
