### PR TITLE
client: reuse `initRetry` function

### PR DESCRIPTION
**Pull request by okJiang**
### What problem does this PR solve?

Issue Number: Ref #4399

### What is changed and how does it work?

```commit-message
```

### Check List

Tests

- Unit test
- Integration test

### Release note

```release-note
None.
```

### CODE REVIEW

**Comment by rleungx** [comment]
Please change the title to `client: reuse initRetry function`.

**Review by JmPotato — APPROVED** [review]

**Review by lhy1024 — APPROVED** [review]

**Pull request merged**
