### PR TITLE
logutil: replace etcd.defaultlogger with pingcap's text encoder

### PR DESCRIPTION
**Pull request by 9547**
### What problem does this PR solve?
I ran into a problem when my _pd.log_ contains the following file contents, the tidb-dashboard could not find any logs from pd's component:

```
{"level":"warn","ts":"2021-03-01...","caller":"clientv3/retry/interceptor.go:61",.....}
{"level":"warn","ts":"2021-03-01...","caller":"clientv3/retry/interceptor.go:61",.....}
```

After some exploration, it turns out that the `SearchLog` interface implemented by the `DiagnosticsServer` requires the log to be in the following format, ref [pingcap/sysutil](https://github.com/pingcap/sysutil/blob/master/search_log.go#L287-L315):

```go
// parses single log line and returns:
// 1. the timesteamp in unix milliseconds
// 2. the log level
// 3. the log item content
//
// [2019/08/26 06:19:13.011 -04:00] [INFO] [printer.go:41] ["Welcome to TiDB."] ["Release Version"=v2.1.14]...
// [2019/08/26 07:19:49.529 -04:00] [INFO] [printer.go:41] ["Welcome to TiDB."] ["Release Version"=v3.0.2]...
// [2019/08/21 01:43:01.460 -04:00] [INFO] [util.go:60] [PD] [release-version=v3.0.2]
// [2019/08/26 07:20:23.815 -04:00] [INFO] [mod.rs:28] ["Release Version:   3.0.2"]
func parseLogItem(s string) (*pb.LogMessage, error) {
	timeLeftBound := strings.Index(s, "[")
	timeRightBound := strings.Index(s, "]")
	if timeLeftBound == -1 || timeRightBound == -1 || timeLeftBound > timeRightBound {
		return nil, fmt.Errorf("invalid log string: %s", s)
	}
	time, err := parseTimeStamp(s[timeLeftBound+1 : timeRightBound])
	if err != nil {
		return nil, err
	}
	levelLeftBound := strings.Index(s[timeRightBound+1:], "[")
	levelRightBound := strings.Index(s[timeRightBound+1:], "]")
	level := ParseLogLevel(s[timeRightBound+1+levelLeftBound+1 : timeRightBound+1+levelRightBound])
	item := &pb.LogMessage{
		Time:    time,
		Level:   level,
		Message: strings.TrimSpace(s[timeRightBound+levelRightBound+2:]),
	}
	return item, nil
}
```
But the previous etcd's default log format is in JSON format: 
[logutil/zap.go#L34](https://github.com/etcd-io/etcd/blob/master/pkg/logutil/zap.go#L34):

```go
// DefaultZapLoggerConfig defines default zap logger configuration.
var DefaultZapLoggerConfig = zap.Config{
	Level: zap.NewAtomicLevelAt(ConvertToZapLevel(DefaultLogLevel)),

	Development: false,
	Sampling: &zap.SamplingConfig{
		Initial:    100,
		Thereafter: 100,
	},

	Encoding: "json",

	// copied from "zap.NewProductionEncoderConfig" with some updates
	EncoderConfig: zapcore.EncoderConfig{
		TimeKey:        "ts",
		LevelKey:       "level",
		NameKey:        "logger",
		CallerKey:      "caller",
		MessageKey:     "msg",
		StacktraceKey:  "stacktrace",
		LineEnding:     zapcore.DefaultLineEnding,
		EncodeLevel:    zapcore.LowercaseLevelEncoder,
		EncodeTime:     zapcore.ISO8601TimeEncoder,
		EncodeDuration: zapcore.StringDurationEncoder,
		EncodeCaller:   zapcore.ShortCallerEncoder,
	},

	// Use "/dev/null" to discard all
	OutputPaths:      []string{"stderr"},
	ErrorOutputPaths: []string{"stderr"},
}
```

If the log file contains lines encoded in JSON, the `DiagnosticsServer` maybe not work as expected, So I replace the etcd log into [pingcap/log](https://github.com/pingcap/log)'s TestEncoder.

### Check List

Tests

- Unit test
- Integration test
- Manual test (add detailed scripts or steps below)
- No code

Code changes

- Has configuration change
- Has HTTP API interfaces change (Don't forget to [add the declarative for API](https://github.com/tikv/pd/blob/master/docs/development.md#updating-api-documentation))
- Has persistent data change

Side effects

- Possible performance regression
- Increased code complexity
- Breaking backward compatibility

Related changes

- PR to update [`pingcap/docs`](https://github.com/pingcap/docs)/[`pingcap/docs-cn`](https://github.com/pingcap/docs-cn):
- PR to update [`pingcap/tidb-ansible`](https://github.com/pingcap/tidb-ansible):
- Need to cherry-pick to the release branch

### CODE REVIEW

**Comment by JmPotato** [comment]
@9547 Please sign off your commit and fix the static check, thx!

**Comment by HunDunDM** [comment]
Thank you for your PR. This issue is a known issue, but it has not been resolved.
If you use the `---log-file`, they should not appear in the log file. Is stdout redirection used?

**Comment by 9547** [comment]
> Thank you for your PR. This issue is a known issue, but it has not been resolved.
> If you use the `--log-file`, they should not appear in the log file. Is stdout redirection used?

etcd's default log handler will write logs into stderr, ref https://github.com/etcd-io/etcd/blob/master/pkg/logutil/zap.go#L52-L53

```go
	OutputPaths:      []string{"stderr"},
	ErrorOutputPaths: []string{"stderr"},
```
So if `--log-file` is specified and no stderr redirected, I think the etcd's log will not write into the log file(not tested).

**Comment by HunDunDM** [comment]
I think it would be a better choice to put `zap.RegisterEncoder` in `pingcap/log`. It is also not recommended to change the constants in `etcd`. It will cause trouble to other dependencies.

We can use
```
logConfig := zap.NewProductionConfig()
logConfig.Encoding = pingcaplog.ZapEncodingName
```
to generate the log configuration and specify it in `clientv3.New` to unify the log format. It requires us to modify in the order of `pingcap/log`,`pingcap/tidb-dashboard`,`tikv/pd`.

**Comment by HunDunDM** [comment]
* Add `zap.RegisterEncoder` to [pingcap/log/log.go/InitLoggerWithWriteSyncer](https://github.com/pingcap/log/blob/8f1e84a3abc8f75ae33a8bee86d561f21057393e/log.go#L57)
* Remove `zap.RegisterEncoder` in [tidb-dashboard/pkg/pd/etcd.go](https://github.com/pingcap/tidb-dashboard/blob/eef5d64046383c015befc1cc960a6ca267a2cd1f/pkg/pd/etcd.go#L30~L40)
* Config clientv3.New in [tidb-dashboard/pkg/pd/etcd.go](https://github.com/pingcap/tidb-dashboard/blob/eef5d64046383c015befc1cc960a6ca267a2cd1f/pkg/pd/etcd.go#L46)
* Config clientv3.New in [pd/server/server.go](https://github.com/tikv/pd/blob/92ddb6269a7640c4024342407ed6caad4da271fe/server/server.go#L299) [pd/server/join/join.go](https://github.com/tikv/pd/blob/92ddb6269a7640c4024342407ed6caad4da271fe/server/join/join.go#L116)

**Comment by 9547** [comment]
> * Add `zap.RegisterEncoder` to [pingcap/log/log.go/InitLoggerWithWriteSyncer](https://github.com/pingcap/log/blob/8f1e84a3abc8f75ae33a8bee86d561f21057393e/log.go#L57)
> * Remove `zap.RegisterEncoder` in [tidb-dashboard/pkg/pd/etcd.go](https://github.com/pingcap/tidb-dashboard/blob/eef5d64046383c015befc1cc960a6ca267a2cd1f/pkg/pd/etcd.go#L30~L40)
> * Config clientv3.New in [tidb-dashboard/pkg/pd/etcd.go](https://github.com/pingcap/tidb-dashboard/blob/eef5d64046383c015befc1cc960a6ca267a2cd1f/pkg/pd/etcd.go#L46)
> * Config clientv3.New in [pd/server/server.go](https://github.com/tikv/pd/blob/92ddb6269a7640c4024342407ed6caad4da271fe/server/server.go#L299) [pd/server/join/join.go](https://github.com/tikv/pd/blob/92ddb6269a7640c4024342407ed6caad4da271fe/server/join/join.go#L116)

Thanks for your advice, I'll try to implement it later tonight. :)

**Comment by HunDunDM** [comment]
Because there are three repo involved, and there are dependencies. We can do it step by step.

**Review by nolouch — APPROVED** [review]

**Review by nolouch — CHANGES_REQUESTED** [review]
cancel

**Comment by JmPotato** [comment]
@HunDunDM Can we approve this PR now? cc @9547

**Comment by HunDunDM** [comment]
> @HunDunDM Can we approve this PR now? cc @9547

Also need to update `tidb-dashboard`.

**Comment by 9547** [comment]
> > @HunDunDM Can we approve this PR now? cc @9547
> 
> Also need to update `tidb-dashboard`.

DONE

**Review by JmPotato — APPROVED** [review]

**Comment by nolouch** [comment]
cc @HunDunDM

**Review by HunDunDM — APPROVED** [review]

**Review by nolouch — APPROVED** [review]

**Pull request merged**
