### PR TITLE
dr-autosync: add config to allow pausing region split

### LINKED ISSUE #4752: Dr-autosync: After recover backup dc, hit error 9005: unavailable region when query one table
### What did you do?
1、Configure a cluster run at dr-auto-sync mode;
2、Down backup dc，run bank workload;
3、Start up backup dc, util replication mode change to sync_recover
4、Down primary dc，recover the cluster from backup dc;
5、Run bank workload again 

### What did you expect to see?
bank account maybe not equal to the original value.

### What did you see instead?

MySQL [bank]> select count(*) from bank2_transaction;
ERROR 9005 (HY000): Region is unavailable

### What version of PD are you using (`pd-server -V`)?
MySQL [(none)]> select type, max(version), max(git_hash) from information_schema.cluster_info group by type;
+------+--------------+------------------------------------------+
| type | max(version) | max(git_hash)                            |
+------+--------------+------------------------------------------+
| pd   | 6.0.0-alpha  | d56b195b72dc006b5232a92d45743480b7460a1c |
| tikv | 6.0.0-alpha  | e1fae9469b33ff1ec4fd66aa143a21a5f30f5aa3 |
| tidb | 6.0.0-alpha  | 9fcc6b090b02c8351aba4ee8a7f072e0e0c840e0 |
+------+--------------+------------------------------------------+
3 rows in set (0.01 sec)

### PR DESCRIPTION
**Pull request by disksing**
### What problem does this PR solve?
Issue Number: ref #4752
Close #4752

If the config option is enabled, PD will not allow region to split during non-sync states. Blocking the processing of askSplit and AskBatchSplit from the PD side should be sufficient. But we subsequently plan to update tikv to avoid generating ask[Batch]Split messages.

```commit-message
```

### Check List

Tests

- Unit test

### Release note

```release-note
None
```

### CODE REVIEW

**Comment by rleungx** [comment]
I think it might be a common requirement, e.g., online recovery may also need this.

**Review by nolouch — APPROVED** [review]
lgtm

**Review by lhy1024 — APPROVED** [review]

**Comment by nolouch** [comment]
need to update kvproto.

**Comment by disksing** [comment]
Please review https://github.com/pingcap/kvproto/pull/899
@nolouch @lhy1024

**Comment by nolouch** [comment]
Merged https://github.com/pingcap/kvproto/pull/899

**Review by nolouch — APPROVED** [review]

**Pull request merged**
