### PR TITLE
client: reduce the retry time before trying follower

### LINKED ISSUE #3502: Spend too much time on retry mechanism before trying follower
### What did you do?

Create a network partition and wait for the recovery of the cluster.

### What did you expect to see?

Retry for a while (within a minute) and start to connect to the follower.

### What did you see instead?

Spend around a few minutes. And the QPS drops for minutes.
Screen Shot 2021-03-23 at 10 55 21 AM

### What version of PD are you using (`pd-server -V`)?
master

### PR DESCRIPTION
**Pull request by rleungx**
### What problem does this PR solve?

Closes #3502. 

### What is changed and how it works?

This PR regards the "Canceled" as a kind of network error.

### Check List

Tests

- Manual test 

Screen Shot 2021-03-23 at 12 08 50 PM
Screen Shot 2021-03-23 at 12 11 52 PM

Related changes

- Need to cherry-pick to the release branch

### Release note

- Reduce time of retrying before trying to connect to the follower

### CODE REVIEW

**Review by JmPotato — APPROVED** [review]

**Review by nolouch — APPROVED** [review]
lgtm

**Comment by nolouch** [comment]
cancel /merge

**Comment by nolouch** [comment]
@rleungx Can you show the test result after this PR?

**Comment by rleungx** [comment]
> @rleungx Can you show the test result after this PR?

Yes. See PR description.

**Pull request merged**
