### PR TITLE
*: upgrade etcd to v3.4.30

### PR DESCRIPTION
**Pull request by JmPotato**
### What problem does this PR solve?

Issue Number: ref #5520.

- Release note: https://github.com/etcd-io/etcd/releases/tag/v3.4.30
- Code changes are caused by https://github.com/etcd-io/etcd/commit/6de105e89b753e851735463844ec41b9967ffe95.

### What is changed and how does it work?

```commit-message
Upgrade etcd to v3.4.30 and adopt the latest code changes.
```

### Check List

Tests

- Unit test
- Integration test

### Release note

```release-note
Upgrade etcd to v3.4.30 to adopt the security patch.
```

### CODE REVIEW

**Review by rleungx — APPROVED** [review]

**Review by HuSharp — APPROVED** [review]

**Comment by wuhuizuo** [comment]
/hold

It needs to be upgrade to "v3.4.29".

@JmPotato

**Pull request merged**
