### PR TITLE
movingaverage: support concurrency safe queue in AvgOverTime (#3506)

### PR DESCRIPTION
**Pull request by ti-srebot**
cherry-pick #3506 to release-4.0
You can switch your code base to this Pull Request by using [git-extras](https://github.com/tj/git-extras):
```bash
# In pd repo:
git pr https://github.com/tikv/pd/pull/3509
```

After apply modifications, you can push your change to this PR via:
```bash
git push git@github.com:ti-srebot/pd.git pr/3509:release-4.0-610c05b7e1c4
```

---

Signed-off-by: yisaer <disxiaofei@163.com>

### What is changed and how it works?
support concurrency safe queue in AvgOverTime

### Check list

Benchmark Test with concurrency queue
```sh
$ go test -bench=BenchmarkCheckRegionFlow -benchtime=10s                                                     
OK: 11 passed
goos: darwin
goarch: amd64
pkg: github.com/tikv/pd/server/statistics
BenchmarkCheckRegionFlow-4       5084605              1996 ns/op
PASS
ok      github.com/tikv/pd/server/statistics    13.584s
```

Benchmark Test with origin queue
```sh
$ go test -bench=BenchmarkCheckRegionFlow -benchtime=10s
OK: 11 passed
goos: darwin
goarch: amd64
pkg: github.com/tikv/pd/server/statistics
BenchmarkCheckRegionFlow-4       6700020              1814 ns/op
PASS
ok      github.com/tikv/pd/server/statistics    15.019s
```

### Release note

* No release note

### CODE REVIEW

**Review by lhy1024 — APPROVED** [review]

**Comment by nolouch** [comment]
@Yisaer  please slove the conflict.

**Review by lhy1024 — APPROVED** [review]

**Review by Yisaer — APPROVED** [review]

**Review by HunDunDM — APPROVED** [review]

**Pull request merged**
