### PR TITLE
cluster: no more redundant etcd writes when `ReportMinResolvedTS` is called

### LINKED ISSUE #5965: Frequent `ReportMinResolvedTS` can cause PD OOM
### What did you do?

ETCD write latency burst up.

image

### What did you expect to see?

There will be no adverse effects.

### What did you see instead?

TiKV keeps reconnecting to PD.
image

The number of ReportMinResolvedTS is increased.
image

PD OOM
image

### What version of PD are you using (`pd-server -V`)?
v6.5.0

### PR DESCRIPTION
**Pull request by HunDunDM**
Signed-off-by: HunDunDM <hundundm@gmail.com>

### What problem does this PR solve?

Issue Number: Close #5965

### What is changed and how does it work?

no more redundant etcd writes when `SetMinResolvedTS` is called

### Check List

Tests

- Unit test
- Manual test (add detailed scripts or steps below)
  - This PR is based on c64be1f858c4c79356fecdc0f232ba786b1c9d70
  - Make `putStoreLocked` called by `SetMinResolvedTS` slower [7a47041](https://github.com/HunDunDM/pd/commit/7a47041234ec37d92774fee2e8f78080e7d865da)
  - `tiup playground v6.5.0 --kv=15 --db=1 --pd=1 --tiflash=0 --pd.binpath=bin/pd-server`
  - The problem can be reproduced in grafana
    - image
    - image
  - `putStoreLocked` was removed in this PR and replaced with `c.core.PutStore(newStore)`, so it can be considered fixed.

Code changes

Side effects

Related changes

- Need to cherry-pick to the release branch

### Release note

```release-note
Fixed an issue where ETCD write delay could cause PD OOM.
```

### CODE REVIEW

**Review by lhy1024 — APPROVED** [review]

**Comment by lhy1024** [comment]
do we need to pick to 6.6？

**Review by nolouch — COMMENTED** [review]
better to add a test. could you add a test or post the manual test result.

**Comment by HunDunDM** [comment]
Adding unit tests to the removed code was difficult, I added a manual test to prove that the original code was buggy.

**Review by nolouch — APPROVED** [review]

**Comment by CabinfeverB** [comment]
It seems that we don't need to persist store in `SetMinResolvedTS`, and persist it only in heartbeat? 
What happens if the PD goes down after SetMinResolvedTS?

**Comment by lhy1024** [comment]
> It seems that we don't need to persist store in `SetMinResolvedTS`, and persist it only in heartbeat? What happens if the PD goes down after SetMinResolvedTS?

we persist min-resolved-ts of the cluster in another goroutine

**Pull request merged**
