### PR TITLE
cgroup: fix the path problem due to special container name

### LINKED ISSUE #6266: cgroup path may be wrong
## Bug Report

See https://github.com/pingcap/tidb/issues/42659 for more details.

### PR DESCRIPTION
**Pull request by rleungx**
### What problem does this PR solve?

Issue Number: Close #6266.

### What is changed and how does it work?
The root cause of this problem is that some container names contain a special symbol. it will lead to getting the wrong cgroup path.

```commit-message
```

### Check List

Tests

- Unit test

### Release note

```release-note
None.
```

### CODE REVIEW

**Review by JmPotato — APPROVED** [review]
LGTM. BTW, is it possible to generate some random container names in the test case to make sure the universality?

**Comment by rleungx** [comment]
> 

Good idea, maybe later.

**Review by lhy1024 — APPROVED** [review]

**Pull request merged**
