### PR TITLE
*: generate the error metafile (#3046)

### PR DESCRIPTION
**Pull request by ti-srebot**
cherry-pick #3046 to release-4.0

---

### What problem does this PR solve?

We need to generate the error metafile according to the RFC of errors

### What is changed and how it works?

This PR use the way provided by TiUP to generate the error metafile. Related to https://github.com/pingcap/tiup/pull/851

### Check List

Tests

- Unit test

Related changes

- Need to cherry-pick to the release branch

### Release note

- generate the metafile of errors

### CODE REVIEW

**Comment by lonng** [comment]
@rleungx Please re-generate the errors.toml for release branch.

**Review by Yisaer — APPROVED** [review]
LGTM

**Pull request merged**
