### PR TITLE
metrics, tso: add more metrics for TSO

### LINKED ISSUE #3713: grafana: "Current Global TSO"
https://github.com/tikv/pd/blob/44aca616fccc25553a133443c78db49ce4e7978f/metrics/grafana/pd.json#L1354-L1438

This currently renders as a number like this:
image

As demonstrated below the value shown here is NOT a TSO-style timestamp, but it is the *physical* part of the TSO timestamp rendered as UNIX timestamp.
```
5.7.25-TiDB-v5.1.0-alpha-13-gd5e0ed0aa-dirty 127.0.0.1:4000  test  SQL  SELECT TIDB_PARSE_TSO((1622099304 * 1000) << 18), FROM_UNIXTIME(1622099304);
+-------------------------------------------+---------------------------+
| TIDB_PARSE_TSO((1622099304 * 1000) << 18) | FROM_UNIXTIME(1622099304) |
+-------------------------------------------+---------------------------+
| 2021-05-27 09:08:24.000000                | 2021-05-27 09:08:24       |
+-------------------------------------------+---------------------------+
1 row in set (0.0013 sec)
```

I would suggest to *either*:

- Correct the label (change "Current Global TSO" to "Current TSO physical UNIX timestamp")
- Change the query to `pd_cluster_tso{tidb_cluster="$tidb_cluster", instance="$instance", dc="global"} * 1000` and set to format to `"format": "dateTimeAsIso"` to display this as a human readable time.
- Change this to show the actual TSO-style timestamp including the logical part.

It *might* be nice to display it like this if that's doable:
```
5.7.25-TiDB-v5.1.0-alpha-13-gd5e0ed0aa-dirty 127.0.0.1:4000  test  SQL  SELECT @a AS `TSO`, TIDB_PARSE_TSO(@a) as `physical timestamp`, @a-((@a >> 18) << 18) 'logical timestamp'\G
*************************** 1. row ***************************
               TSO: 425223599947776123
physical timestamp: 2021-05-27 09:08:24.000000
 logical timestamp: 123
```

### LINKED ISSUE #3720: Add metics for Global TSO synchronization progress
### Describe your feature request related problem

After #3390 is merged, the Global TSO synchronization progress has a complex logic. To address potential problems more easily, we need to add some metrics for it.

### Describe the feature you'd like

Add metics for Global TSO synchronization progress.

### PR DESCRIPTION
**Pull request by JmPotato**
Signed-off-by: JmPotato <ghzpotato@gmail.com>

### What problem does this PR solve?

Close #3720, close #3713. Add more metrics for TSO.

### What is changed and how it works?

* Add more events for TSO.
* Track TSO update time and Global TSO sync RTT.
* Add more detailed TSO Grafana panels.

### Check List

Tests

- Unit test
- Integration test
- Manual test (add detailed scripts or steps below)

图片

图片

### Release note

```release-note
None.
```

### CODE REVIEW

**Comment by JmPotato** [comment]
cc @dveeden

**Review by dveeden — APPROVED** [review]

**Review by nolouch — COMMENTED** [review]
Because the Global/Local TSO is not published, I more like the metrics not relative it. maybe add a category with some (experimental) comments.

**Comment by JmPotato** [comment]
> Condiser the Global/Local TSO is not published, I more like the metrics not relative it. maybe add a category with some (experimental) comments.

I have taken this into my consideration, the new panels added are quite general to use rather than a Global/Local TSO feature only. If necessary, I can change the description "Current Global TSO" back to "Current TSO".

**Review by disksing — APPROVED** [review]

**Comment by nolouch** [comment]
> > Condiser the Global/Local TSO is not published, I more like the metrics not relative it. maybe add a category with some (experimental) comments.
> 
> @nolouch I have taken this into my consideration, the new panels added are quite general to use rather than a Global/Local TSO feature only, they are only about Global TSO which is not misleading though. If necessary, I can change the description "Current Global TSO" back to "Current TSO".
Ok, at least Current TSO. but the TSO gap always empty will confuse users.

**Comment by JmPotato** [comment]
> Ok, at least back to "Current TSO". but the TSO gap always empty will confuse users.

It won't be empty. At least a "global" will exist.

**Comment by nolouch** [comment]
> > Ok, at least back to "Current TSO". but the TSO gap always empty will confuse users.
> 
> It won't be empty. At least a "global" will exist.

`TSO gap` will always no data:
image

**Comment by JmPotato** [comment]
> > > Ok, at least back to "Current TSO". but the TSO gap always empty will confuse users.
> > 
> > 
> > It won't be empty. At least a "global" will exist.
> 
> `TSO gap` will always no data, many users will be. ]
> image

I think you should also update your PD.

**Review by nolouch — APPROVED** [review]
lgtm

**Pull request merged**
