### PR TITLE
autoscaling/prometheus.go tidbSumCPUUsageMetricsPattern problem

### PR DESCRIPTION
**Pull request by shenzhengcmss**
### What problem does this PR solve?

autoscaling about tidbSumCPUUsageMetricsPattern is wrong , result is empty.
image

### What is changed and how it works?
tidbSumCPUUsageMetricsPattern base on component="tidb",will return the correctt result
image

### Check List

Tests

- Unit test
- Integration test
- Manual test (add detailed scripts or steps below)
- No code

Code changes

- Has configuration change
- Has HTTP API interfaces change (Don't forget to [add the declarative for API](https://github.com/tikv/pd/blob/master/docs/development.md#updating-api-documentation))
- Has persistent data change

Side effects

- Possible performance regression
- Increased code complexity
- Breaking backward compatibility

Related changes

- PR to update [`pingcap/docs`](https://github.com/pingcap/docs)/[`pingcap/docs-cn`](https://github.com/pingcap/docs-cn):
- PR to update [`pingcap/tidb-ansible`](https://github.com/pingcap/tidb-ansible):
- Need to cherry-pick to the release branch

### CODE REVIEW

**Comment by shenzhengcmss** [comment]
\cc   @rleungx @Yisaer

**Comment by nolouch** [comment]
Thanks, @shenzhengcmss, What is the version of tidb and tidb operator you use?

**Comment by shenzhengcmss** [comment]
@nolouch pingcap/tidb-operator v1.2.0-alpha.1, this version autoscaler is based on pdplan, tidb-operator v1.1.9 is directly to query prometheus, there are the same problems. Tidb-operator serve many clusters,The best way to query with cluster name parameters  for distinct different cluster. tidbSumCPUUsageMetricsPattern = `sum(increase(process_cpu_seconds_total{clusters="%s",job="tidb"}[%s])) by (instance, kubernetes_namespace)`

**Comment by shenzhengcmss** [comment]
\cc @rleungx @Yisaer  @nolouch

**Review by Yisaer — APPROVED** [review]
LGTM

**Comment by Yisaer** [comment]
@shenzhengcmss  plz fix the DCS check

**Review by rleungx — APPROVED** [review]

**Comment by rleungx** [comment]
BTW, does the operator need to be changed also?

**Comment by shenzhengcmss** [comment]
> @shenzhengcmss plz fix the DCO check
I Re submit with user information,this will success to meet DCO check

**Comment by rleungx** [comment]
I'm going to merge this PR, thanks for your contribution!

**Pull request merged**
