### PR TITLE
doc: update CONTRIBUTING.md and pr template

### LINKED ISSUE #4603: update PR template for linking issue and commit message #11886
see https://github.com/tikv/community/pull/162

### PR DESCRIPTION
**Pull request by zhangyangyu**
### What problem does this PR solve?

Issue Number: close #4603 

### Release note

```release-note
Please add a release note.

If you don't think this PR needs a release note then fill it with None.
```

### CODE REVIEW

**Review by nolouch — APPROVED** [review]

**Comment by nolouch** [comment]
Thanks!
/merge

**Review by disksing — APPROVED** [review]

**Pull request merged**
