### PR TITLE
Fix typo in keyspace config

### PR DESCRIPTION
**Pull request by wwu**
Correct "keyspaces" to "keyspace" as referred in code: https://github.com/tikv/pd/blob/4a7bffcb3baf7a8e2515e70834d8567bc17439da/server/config/config.go#L166C1-L167C1

### What problem does this PR solve?

Issue Number: Ref #4399

### What is changed and how does it work?

```commit-message
```

### Check List

Tests

- Unit test
- Integration test
- Manual test (add detailed scripts or steps below)
- No code

Code changes

- Has the configuration change
- Has HTTP API interfaces changed (Don't forget to [add the declarative for the new API](https://github.com/tikv/pd/blob/master/docs/development.md#updating-api-documentation))
- Has persistent data change

Side effects

- Possible performance regression
- Increased code complexity
- Breaking backward compatibility

Related changes

- PR to update [`pingcap/docs`](https://github.com/pingcap/docs)/[`pingcap/docs-cn`](https://github.com/pingcap/docs-cn):
- PR to update [`pingcap/tiup`](https://github.com/pingcap/tiup):
- Need to cherry-pick to the release branch

### Release note

```release-note
None.
```

### CODE REVIEW

**Review by rleungx — APPROVED** [review]

**Comment by rleungx** [comment]
Please sign DCO.

**Review by lhy1024 — APPROVED** [review]

**Pull request merged**
