### PR TITLE
chore(dashboard): update TiDB Dashboard to v7.1.4-d74e7a85 [release-7.1]

### PR DESCRIPTION
**Pull request by baurine**
### What problem does this PR solve?

Issue Number: ref #4257 #7561 

Update TiDB Dashboard to [v7.1.4-d74e7a85](https://github.com/pingcap/tidb-dashboard/releases/tag/v7.1.4-d74e7a85).

### Release note

```release-note
None
```

image

### CODE REVIEW

**Review by mornyx — APPROVED** [review]

**Review by rleungx — APPROVED** [review]

**Comment by rleungx** [comment]
The data race is fixed by https://github.com/tikv/pd/pull/6370

**Pull request merged**
