### PR TITLE
ci: upgrade go version to 1.18 in github action

### PR DESCRIPTION
**Pull request by nolouch**
Signed-off-by: nolouch <nolouch@gmail.com>

### What problem does this PR solve?

Issue Number: ref https://github.com/tikv/pd/issues/4710

### What is changed and how it works?

```commit-message
ci: upgrade go version to 1.18 in github action
```

### Check List

Tests

- Unit test
- Integration test

### Release note

```release-note
None
```

### CODE REVIEW

**Review by JmPotato — APPROVED** [review]
LGTM

**Comment by JmPotato** [comment]
Should we also update the TSO tests?

**Comment by nolouch** [comment]
cannot update check to v1.18, https://github.com/pingcap/tidb/issues/32874

**Pull request merged**
