### PR TITLE
schedule: not limit remove peer of the down store

### LINKED ISSUE #4090: Scheduling is not restricted by store limit when repairing down-peer
### Describe your feature request related problem

Currently, when repairing down-peer, it will be restricted by store-remove-limit of that store. By default, the upper limit of repairs per hour is 900.

### Describe the feature you'd like

Scheduling is not restricted by store-remove-limit of that store when repairing down-peer

### PR DESCRIPTION
**Pull request by rleungx**
### What problem does this PR solve?

Close #4090.

### What is changed and how it works?

This PR adds a flag in the remove peer step to let the store limit not work when the remove store is down.

### Check List

Tests

- Unit test

### Release note

```release-note
None
```

### CODE REVIEW

**Review by disksing — APPROVED** [review]

**Review by nolouch — APPROVED** [review]

**Comment by HunDunDM** [comment]
I will have no way to limit it?

**Comment by rleungx** [comment]
@HunDunDM @nolouch PTAL

**Review by nolouch — APPROVED** [review]

**Pull request merged**
