### PR TITLE
Force evict leaders in the store when make it offline

### PR DESCRIPTION
**Pull request by xuhui-lu**
### Check List

Tests

- Unit test
- Integration test
- Manual test (add detailed scripts or steps below)
- No code

Code changes

- Has configuration change
- Has HTTP API interfaces change (Don't forget to [add the declarative for API](https://github.com/tikv/pd/blob/master/docs/development.md#updating-api-documentation))
- Has persistent data change

Side effects

- Possible performance regression
- Increased code complexity
- Breaking backward compatibility

Related changes

- PR to update [`pingcap/docs`](https://github.com/pingcap/docs)/[`pingcap/docs-cn`](https://github.com/pingcap/docs-cn):
- PR to update [`pingcap/tidb-ansible`](https://github.com/pingcap/tidb-ansible):
- Need to cherry-pick to the release branch

### Release note

```release-note
Please add a release note.

If you don't think this PR needs a release note then fill it with None.
```

### CODE REVIEW

**Comment by nolouch** [comment]
It's better to build [the operator](https://github.com/tikv/pd/blob/master/server/schedule/checker/rule_checker.go#L104-L114) by randomly transfer the leader if the region's leader store is Offline.  As @rleungx  mentions in https://github.com/tikv/pd/issues/3563, it's may have corner case.

**Comment by nolouch** [comment]
Hi @xuhui-lu, would you like to do it in the other way?

**Comment by xuhui-lu** [comment]
> Hi @xuhui-lu, would you like to do it in the other way?

yea, that makes sense to me. Iet me take a look at #3563 first.

**Comment by nolouch** [comment]
@xuhui-lu  I have fire a PR https://github.com/tikv/pd/pull/3730, would please do some review?

**Comment by xuhui-lu** [comment]
> @xuhui-lu I have fire a PR #3730, would please do some review?

cool, I will take a look at it.

**Pull request closed without merging**
