### PR TITLE
*: Bug Fix/CLUSTER_INFO system table may not work after PD is scaled-in (#2830)

### PR DESCRIPTION
**Pull request by ti-srebot**
cherry-pick #2830 to release-4.0

---

### What problem does this PR solve?

Issue Number: close https://github.com/pingcap/tidb/issues/18990

Problem Summary:

CLUSTER_INFO system table may not work after PD is scaled-in

### What is changed and how it works?

What's Changed:

Add the GetMemberInfo function to client interface, use grpc GetMembers() to get the pd members info.

How it Works:

 use grpc GetMembers() to get the pd members info.

### Related changes

- PR to update `pingcap/pd/client/client.go`;
- Need to cherry-pick to the release branch

### Check List 

Tests

- Unit test
- Manual test (add detailed scripts or steps below)

steps:

* use tiup playground scale-out --pd 1 to scale out pd
* use mysql to connect TiDB
* `select * from  INFORMATION_SCHEMA.CLUSTER_INFO; `to test scale out and scale in

Side effects

- Performance regression
    - Consumes more CPU

### Release note 

* add GetMemberInfo() function to get pd member info

### CODE REVIEW

**Comment by crazycs520** [comment]
@Yisaer  @nolouch  PTAL

**Review by nolouch — APPROVED** [review]
LGTM

**Review by Yisaer — APPROVED** [review]
LGTM

**Pull request merged**
