### PR TITLE
fixbug-#4422

### PR DESCRIPTION
**Pull request by Dagon0577**
### What problem does this PR solve?

This is to solve the error skip code found in https://github.com/tikv/pd/issues/4422
ref #4422
### What is changed and how it works?
we should gets the total count of a store's leader and follower RegionInfo by storeID rather than get the Region count of the store.
### Check List

Tests

- Unit test
- Integration test

### Release note

```release-note
None.
```

### CODE REVIEW

**Review by rleungx — APPROVED** [review]
Thanks. LGTM.

**Review by nolouch — APPROVED** [review]

**Pull request merged**
