### PR TITLE
client: add max error retry time for client

### PR DESCRIPTION
**Pull request by glorv**
### What problem does this PR solve?

The current implementation will retry upto 100 times if connect meets error. Thus, if use misconfig the pd address, the `pd.NewClient` will return an error after 100s which is too slow and seems like a bug in the view of a user.

See: https://github.com/pingcap/tidb-lightning/issues/462

### What is changed and how it works?
Add a config `WithMaxErrorRetry` to allow pd client custom connect max retry time when meets error.

### Check List

Tests

- Unit test

Code changes

Side effects

Related changes
- Need to cherry-pick to the release branch

### Release note
- Support config client max error retry times

### CODE REVIEW

**Comment by glorv** [comment]
@3pointer @overvenus PTAL

**Comment by overvenus** [comment]
LGTM

**Comment by JmPotato** [comment]
@glorv Please update the branch to merge this PR.

**Pull request merged**
