### PR TITLE
schedule: fix panic during hot schedule (#3483)

### PR DESCRIPTION
**Pull request by ti-srebot**
cherry-pick #3483 to release-4.0
You can switch your code base to this Pull Request by using [git-extras](https://github.com/tj/git-extras):
```bash
# In pd repo:
git pr https://github.com/tikv/pd/pull/3485
```

After apply modifications, you can push your change to this PR via:
```bash
git push git@github.com:ti-srebot/pd.git pr/3485:release-4.0-f82f2d82c2d6
```

---

Signed-off-by: Song Gao <disxiaofei@163.com>

### What problem does this PR solve?

`hot-region` scheduler may cause PD panic in the following order:

1.  load `storesLoads` before hot region scheduling
```golang
	storesLoads := cluster.GetStoresLoads()
```
2. receive new `PutStore` request
```golang
// put Store in grpc_service.go
if err := rc.PutStore(store); err != nil {
	return nil, status.Errorf(codes.Unknown, err.Error())
}
```
3. select candidates from `raft.cluster`
```golang
candidates = bs.cluster.GetStores()
```

This will cause make `pickDstStores` panic in following code because `stLoadDetail` didn't have the storeID which candidates hold as it was newly put before.
```golang
detail := bs.stLoadDetail[store.GetID()]
```

### What is changed and how it works?

Make the candidates should be searched from `stLoadDetail` during hot region schedule

### Check List

Tests

- Unit test

### Release note

* No release note

### CODE REVIEW

**Review by lhy1024 — COMMENTED** [review]
plz fix confilct

**Review by lhy1024 — APPROVED** [review]

**Review by nolouch — APPROVED** [review]

**Review by nolouch — APPROVED** [review]

**Review by HunDunDM — APPROVED** [review]

**Pull request merged**
