### PR TITLE
scheduler: cache statistics to avoid frequent copy

### PR DESCRIPTION
**Pull request by lhy1024**
Signed-off-by: lhy1024 <admin@liudos.us>

### What problem does this PR solve?

Issue Number: Ref #5692

### What is changed and how does it work?

```commit-message
```

### Check List

Tests

- Unit test

### Release note

```release-note
None.
```

### CODE REVIEW

**Comment by rleungx** [comment]
Does this affect the hot region scheduling?

**Comment by lhy1024** [comment]
> Does it affect the hot region scheduling?

Before this PR, hot scheduler gets hot statistics info by every schedule, usually 10ms. But in fact, we don’t need such high precision. 

I think 1 second is enough. In fact, the minimum time granularity of statistical information is also one second. Currently, the interval of store heartbeat and region heartbeat are also 10 seconds and 60 seconds.

**Review by HunDunDM — APPROVED** [review]

**Review by rleungx — APPROVED** [review]

**Pull request merged**
