### PR TITLE
build: add `--always` to `git describe`

### PR DESCRIPTION
**Pull request by HunDunDM**
Signed-off-by: Zheng Xiangsheng <hundundm@gmail.com>

### What problem does this PR solve?

* In Travis CI, `fatal: No names found, cannot describe anything.` and `-ldflags '-X "github.com/tikv/pd/server/versioninfo.PDReleaseVersion="` can be described. 
* Example: https://travis-ci.org/github/tikv/pd/builds/741036669

### What is changed and how it works?

* build: add `--always` to `git describe`
* In the CI of this PR, `fatal: No names found, cannot describe anything.` will disappear.

### Check List

Related changes

- Need to cherry-pick to the release branch

### Release note

- No release note

### CODE REVIEW

**Comment by rleungx** [comment]
Could you please explain more about this problem?

**Comment by HunDunDM** [comment]
> Could you please explain more about this problem?

In Travis CI, `git checkout` does not get tag information. If there is no `--always`, `git describe
` will print an error and return an empty string. Otherwise, it will return a hash string.

This problem will not cause CI errors.

**Review by lhy1024 — APPROVED** [review]

**Comment by rleungx** [comment]
I receive `fatal: No names found, cannot describe anything` after updating the makefile.

**Comment by HunDunDM** [comment]
> I receive `fatal: No names found, cannot describe anything` after updating the makefile.

Please explain the reproduction steps.

**Pull request merged**
