### PR TITLE
*: fix the missing log panic

### LINKED ISSUE #6257: output panic log to pd.log
### What did you do?
no mater

### What did you expect to see?
output panic log to pd.log

### What did you see instead?
no panic log in pd.log if pd panic

### PR DESCRIPTION
**Pull request by rleungx**
### What problem does this PR solve?

Issue Number: Close #6257

### What is changed and how does it work?

```commit-message
```

### Check List

Tests

- Unit test

### Release note

```release-note
None.
```

### CODE REVIEW

**Review by HuSharp — APPROVED** [review]

**Review by HuSharp — COMMENTED** [review]
May need a way to redirect logs? Feels like omissions are hard to eliminate

**Comment by rleungx** [comment]
@HuSharp Do we need to cherry-pick it?

**Comment by HuSharp** [comment]
> @HuSharp Do we need to cherry-pick it?

It would be nice to have, IMO.

**Pull request merged**
