### PR TITLE
api: support more profile API

### PR DESCRIPTION
**Pull request by rleungx**
### What problem does this PR solve?

Sometimes the trace may be important for debugging.

### What is changed and how it works?

This PR adds more profile API.

### Check List

Tests

- Unit test

### CODE REVIEW

**Review by Yisaer — APPROVED** [review]
LGTM

**Comment by nolouch** [comment]
Can we support `/debug/zip` like TiDB?

**Review by nolouch — APPROVED** [review]

**Comment by rleungx** [comment]
> Can we support `/debug/zip` like TiDB?

Yes, of course. If necessary, I will add it later.

**Comment by nolouch** [comment]
@rleungx Let us do it in another PR.

**Pull request merged**
