### PR TITLE
test: fix data race in store limit test

### LINKED ISSUE #4906: Store Limit test happen Data race
### Which jobs are failing
[chunks (2)](https://github.com/tikv/pd/runs/6333649140?check_suite_focus=true#logs)

### CI link
https://github.com/tikv/pd/runs/6333649140?check_suite_focus=true

### Reason for failure (if possible)
data race

### PR DESCRIPTION
**Pull request by CabinfeverB**
Signed-off-by: Cabinfever_B <cabinfeveroier@gmail.com>

### What problem does this PR solve?

Issue Number: Close #4906

### What is changed and how does it work?

clone config

```commit-message
fix data race in store limit test
```

### Check List

Tests

- Unit test

### Release note

```release-note
None.
```

### CODE REVIEW

**Review by lhy1024 — APPROVED** [review]

**Comment by rleungx** [comment]
Do other tests have this problem?

**Review by bufferflies — APPROVED** [review]

**Review by AndreMouche — APPROVED** [review]
LGTM, good catch!

**Comment by CabinfeverB** [comment]
> Do other tests have this problem?

I found the trigger for the data race needs two conditions, the first is there is a point which is direct from `persistOptions` , the second is the need to use the Set method in the ` Server ` (the Set method in the ` Server ` will not Clone, `PersistOptions` will)

**Review by rleungx — APPROVED** [review]

**Pull request merged**
