### PR TITLE
chore: update tidb-dashboard to v2023.08.15.1

### LINKED ISSUE #6966: dashboard: fix export statement failed issue and support config ngm timeout param
## Development Task

Related tidb-dashboard release: https://github.com/pingcap/tidb-dashboard/pull/1572

### PR DESCRIPTION
**Pull request by baurine**
### What problem does this PR solve?

Issue Number: Close #6966 

### What is changed and how does it work?

```commit-message
1. This PR fixed the statements list export failed issue
2. This PR support config the ngm component timeout param
```

### Release note

```release-note
None.
```

### Test

```
make pd-server
tiup playground v6.5.3 --tiflash 0 --pd.binpath /mnt/bao/codes/work/pd/bin/pd-server
```

image

### CODE REVIEW

**Comment by baurine** [comment]
This PR needs to be cherry-pick to PD 7.1 and 6.1 as well.

**Comment by CabinfeverB** [comment]
ok-to-test

**Review by CabinfeverB — APPROVED** [review]

**Review by HuSharp — APPROVED** [review]

**Comment by HuSharp** [comment]
@baurine can u paste a picture for running this pr?

**Comment by baurine** [comment]
> @baurine can u paste a picture for running this pr?

ok, sure, let me update it soon.

**Comment by baurine** [comment]
Please help cherry-pick this PR to release-7.1 and release-6.1 branch, thanks~

**Pull request merged**
