### PR TITLE
Add more legend for cluster metrics

### LINKED ISSUE #3531: The system status can not show well when using TiUP to deploy the cluster
### What did you do?

Use TiUP to deploy a cluster.

### What did you expect to see?

We can get the CPU or memory status from Grafana

### What did you see instead?

Screen Shot 2021-03-25 at 5 28 02 PM

### What version of PD are you using (`pd-server -V`)?
master

### PR DESCRIPTION
**Pull request by lhy1024**
### What problem does this PR solve?

To close #3531

Previous legend may not be compatible with operator and tiup deployed clusters

### What is changed and how it works?

replace instance with job

### Check List

Tests

- Unit test
- Integration test
- Manual test (add detailed scripts or steps below)

Test in k8s cluster
image

Test in tiup cluster
image

### Release note

- No release note

### CODE REVIEW

**Comment by lhy1024** [comment]
@rleungx would you like to add a manual test for tiup cluster>

**Review by rleungx — APPROVED** [review]
LGTM, except the duplicated field in K8s environment

**Review by HunDunDM — APPROVED** [review]

**Pull request merged**
