### PR TITLE
dr-autosync: improve state file content

### LINKED ISSUE #4341: dr-autosync: improve state file format
## Development Task

When the state is not `sync-recover`, the `recover-start` is not initialized. In the file, it shows `0001-01-01T00:00:00Z`.

It would be better to hide the time.

### PR DESCRIPTION
**Pull request by disksing**
Signed-off-by: disksing <i@disksing.com>

### What problem does this PR solve?

close #4341

### What is changed and how it works?

- use `*time.Time` instead of `time.Time`
- add test
- add some logs

### Check List

Tests

- Unit test

Code changes
- Has persistent data change

Related changes
- Need to cherry-pick to the release branch

### Release note

```release-note
Improve DR_STATE file content format
```

### CODE REVIEW

**Review by lhy1024 — APPROVED** [review]

**Review by nolouch — APPROVED** [review]

**Comment by disksing** [comment]
@nolouch why cancel merge?

**Pull request merged**
