### PR TITLE
hotfix: Upgrade Third-Party Dependencies, Go Version, and Base Image in v6.5.7

### LINKED ISSUE #8753: Upgrade Third-Party Dependencies, Go Version, and Base Image in v6.5.7
To ensure long-term stability, compatibility, and performance of our project, this issue proposes an upgrade to the following components:

- Third-party dependencies
- Go version
- Base image

### PR DESCRIPTION
**Pull request by lhy1024**
### What problem does this PR solve?

Issue Number: Close #8753

### What is changed and how does it work?

```commit-message
```

### Check List

Tests

- Unit test

### Release note

```release-note
None.
```

### CODE REVIEW

**Comment by purelind** [comment]
> Details

Please wait a moment, I will adjust the Go version of the build environment corresponding to this branch.

**Comment by nolouch** [comment]
Why is it necessary to only apply a hotfix? Does the release-6.5 branch need to have its dependencies updated?

**Comment by lhy1024** [comment]
> Why is it necessary to only apply a hotfix? Does the release-6.5 branch need to have its dependencies updated?

It is only some request from customers

**Review by rleungx — APPROVED** [review]

**Comment by wuhuizuo** [comment]
please wait for #8811

**Review by wuhuizuo — APPROVED** [review]

**Review by nolouch — APPROVED** [review]

**Pull request merged**
