### PR TITLE
*: fix default config when using config file

### PR DESCRIPTION
**Pull request by rleungx**
### What problem does this PR solve?

Issue Number: Ref #5836.

### What is changed and how does it work?

This PR removes all configs in the command line and lets adjust to set the default value if there is no one.

```commit-message
```

### Check List

Tests

- Manual test 

Use the config file to set `client-urls` and `peer-urls`, then start the server to validate if it is right.

### Release note

```release-note
None.
```

### CODE REVIEW

**Comment by rleungx** [comment]
@glorv PTAL

**Review by bufferflies — APPROVED** [review]

**Review by lhy1024 — APPROVED** [review]

**Review by glorv — COMMENTED** [review]
LGTM

**Review by JmPotato — APPROVED** [review]

**Pull request merged**
