### PR TITLE
*: make TestScheduler stable

### LINKED ISSUE #5667: `pdctl/TestScheduler` is unstable
https://github.com/tikv/pd/actions/runs/3368718923/jobs/5587582938

### PR DESCRIPTION
**Pull request by lhy1024**
Signed-off-by: lhy1024 <admin@liudos.us>

### What problem does this PR solve?

Issue Number: Close #5667.

### What is changed and how does it work?
Only check necessary params.

```commit-message
```

### Check List

Tests

- Unit test

### Release note

```release-note
None
```

### CODE REVIEW

**Review by HunDunDM — APPROVED** [review]

**Comment by rleungx** [comment]
Can you describe more about why this PR can fix the problem?

**Comment by lhy1024** [comment]
> Can you describe more about why this PR can fix the problem?

It is similar with last fix, which only judge necessary params.

**Review by nolouch — APPROVED** [review]

**Review by nolouch — APPROVED** [review]
lgtm

**Review by nolouch — APPROVED** [review]
lgtm

**Pull request merged**
