### PR TITLE
Update TiDB Dashboard to v2021.11.08.1 [release-5.3]

### PR DESCRIPTION
**Pull request by baurine**
Signed-off-by: baurine <2008.hbl@gmail.com>

### What problem does this PR solve?

Update TiDB Dashboard to v2021.11.08.1.

Upstream commit: https://github.com/pingcap/tidb-dashboard/commit/80363dfbe88469e288d0a0a68204c64ee31ef9cd .

**TiDB Dashboard related PRs:**

- https://github.com/pingcap/tidb-dashboard/pull/1038
- https://github.com/pingcap/tidb-dashboard/pull/1043
- https://github.com/pingcap/tidb-dashboard/pull/1044
- https://github.com/pingcap/tidb-dashboard/pull/1048

### Release note

```release-note
None
```

### CODE REVIEW

**Comment by baurine** [comment]
This is a cherry-pick for PR #4297 

As a ref: This PR includes the new wordings for continuous profiling.

**Review by JmPotato — APPROVED** [review]

**Review by crazycs520 — APPROVED** [review]
LGTM

**Comment by baurine** [comment]
TiDB Dashboard related PRs:

- https://github.com/pingcap/tidb-dashboard/pull/1038
- https://github.com/pingcap/tidb-dashboard/pull/1043
- https://github.com/pingcap/tidb-dashboard/pull/1044
- https://github.com/pingcap/tidb-dashboard/pull/1048

**Review by nolouch — APPROVED** [review]

**Pull request merged**
