### PR TITLE
*: check if GetStore returns nil

### LINKED ISSUE #4344: PD panic after scale in TiKV node
## Bug Report

stack:
middle_img_v2_906e6626-9c0f-48a3-9515-0fe4e28c5cfg

### What version of PD are you using (`pd-server -V`)?
master

### PR DESCRIPTION
**Pull request by disksing**
close #4344

Signed-off-by: disksing <i@disksing.com>

### What problem does this PR solve?
If we use `remove tombstone`, `GetStore` may return nil. We should check it.

### Check List

Tests

- Unit test

Related changes
- Need to cherry-pick to the release branch

### Release note

```release-note
Fix panic issue after TiKV node scales in
```

### CODE REVIEW

**Review by lhy1024 — APPROVED** [review]

**Review by JmPotato — APPROVED** [review]

**Review by rleungx — APPROVED** [review]

**Comment by JmPotato** [comment]
Wait for adding a test to merge.

**Pull request merged**
