### PR TITLE
Update TiDB Dashboard to v2022.07.27.1, ref #4257

### PR DESCRIPTION
**Pull request by YiniXu9506**
Signed-off-by: YiniXu9506 <xuyini@pingcap.com>

### What problem does this PR solve?

Issue Number: Close https://github.com/tikv/pd/issues/5366
Update TiDB Dashboard to v2022.07.27.1.

### Check List

Tests

- No code

Related changes

- Need to cherry-pick to the release branch
    - 6.2

### Release note

```release-note
- Updates metrics query.
- Renames `metrics` to `monitoring` on TiDB Dashboard.
```

### CODE REVIEW

**Comment by YiniXu9506** [comment]
@shhdgit PTAL

**Review by shhdgit — APPROVED** [review]
LGTM.

**Review by nolouch — APPROVED** [review]
LGTM. we need a separate issue, and it's type should be `type/bug`, then we can triage it to the release 6.2 branch.

**Pull request merged**
