### PR TITLE
fix empty http response in scheduler

### PR DESCRIPTION
**Pull request by lhy1024**
Signed-off-by: lhy1024 <admin@liudos.us>

### What problem does this PR solve?

we should call `.Error` to convert `error` to `string`, otherwise we will get an empty result.

### Check List

Tests

- Unit test

### CODE REVIEW

**Comment by lhy1024** [comment]
@howardlau1999 PTAL

**Comment by lhy1024** [comment]
cc @nolouch 
do we need to cherry-pick it to 4.0?

**Review by rleungx — APPROVED** [review]
LGTM

**Comment by howardlau1999** [comment]
LGTM

**Pull request merged**
