### PR TITLE
Update `average over time`

### PR DESCRIPTION
**Pull request by lhy1024**
### What problem does this PR solve?

Previously, we filled the aot and then emptied it, which not only wasted some data, but also increased latency.

### What is changed and how it works?

Now we will save the data, while continuing to take the data in the aot size, and for the extra margin in the first data in the queue, we will make the cut.

So we can translate the problem into another one: Taking the flow data from the heartbeat, imagining it as a histogram with area `delta` and width `interval`, and then take the area of `aot_size` and calculate their heights.

image

It also a part of #3201 

### Check List

Tests

- Unit test

### CODE REVIEW

**Review by HunDunDM — APPROVED** [review]

**Review by disksing — APPROVED** [review]

**Comment by nolouch** [comment]
Does need pick to  4.0？

**Comment by lhy1024** [comment]
> Does need pick to 4.0？

I think it would be better to merge it with other statistical modifications.

**Comment by disksing** [comment]
CI broken. Use super power.

**Pull request merged**
