### PR TITLE
dashboard: Update TiDB Dashboard to v2021.06.15.1

### PR DESCRIPTION
**Pull request by shhdgit**
Signed-off-by: Suhaha jklopsdfw@gmail.com

### What problem does this PR solve?

Update to TiDB Dashboard v2021.06.15.1

### Check List

Tests

- Manual test (add detailed scripts or steps below)

Related changes

- Need to cherry-pick to the release branch

### Release note

```release-note
Update TiDB Dashboard to v2021.06.15.1
```

### CODE REVIEW

**Review by breeswish — APPROVED** [review]

**Comment by breeswish** [comment]
@HunDunDM PTAL, thanks!

**Review by HunDunDM — APPROVED** [review]

**Pull request merged**
