### PR TITLE
Fix hot write leader scheduler

### LINKED ISSUE #3409: Unnecessary transfer hot write leader schedule
### What did you do?

Perform hotspot write tests

1tidb 10c + 1 pd 5c + 8 tikv 10c 

`go-ycsb run mysql -P workloady -p threadcount=200 -p mysql.host=10.68.107.136  -p mysql.port=4000`

```
workload=core
recordcount=210000000
operationcount=100000000000
threadcount=200
fieldcount=2
fieldlength=512
readallfields=true
fieldlengthdistribution=constant
readproportion=0
updateproportion=0
insertproportion=1
scanproportion=0
table=x23
requestdistribution=uniform

```

### What did you expect to see?

No additional scheduling

### What did you see instead?

Frequent scheduling exists

image

### What version of PD are you using (`pd-server -V`)?
https://github.com/tikv/pd/commit/85e22ef6ba51f02cb885c583ff471e4a8e2d665c

### PR DESCRIPTION
**Pull request by lhy1024**
### What problem does this PR solve?

close #3409 

### What is changed and how it works?

add additional judgment

image

left: master
right: master with this pr

### Check List

Tests

- Unit test

### Release note

- Fix hot write leader scheduler to avoid unnecessary scheduling

### CODE REVIEW

**Comment by rleungx** [comment]
Will this PR make the written bytes of the hot leader more balanced?

**Comment by lhy1024** [comment]
> Will this PR make the written bytes of the hot leader more balanced?

Maybe. This PR will reduce unnecessary schedule.

**Review by HunDunDM — APPROVED** [review]

**Review by nolouch — APPROVED** [review]

**Pull request merged**
