### PR TITLE
core:  clean some remain code about deviation filter.

### LINKED ISSUE #5328: clean some remain code about deviation
## Development Task
The deviation filter has been removed since v5.2.0 , it should removed:
https://github.com/tikv/pd/blob/a5c00c0c7ef3d933416c53638694f4457140fd9d/server/core/store_stats.go#L48-L61

### PR DESCRIPTION
**Pull request by bufferflies**
### What problem does this PR solve?

Issue Number: Close #5328

### What is changed and how does it work?

```commit-message
```

### Check List

Tests

- Unit test

Code changes

Side effects

Related changes

### Release note

```release-note
None.
```

### CODE REVIEW

**Review by rleungx — APPROVED** [review]

**Review by AndreMouche — APPROVED** [review]
LGTM

**Comment by nolouch** [comment]
@bufferflies  ci failed.

**Comment by nolouch** [comment]
cc @bufferflies  DCO failed.

**Pull request merged**
