### PR TITLE
core: fix the wrong statistics of the region tree

### PR DESCRIPTION
**Pull request by rleungx**
Signed-off-by: Ryan Leung <rleungx@gmail.com>

### What problem does this PR solve?

Issue Number: Close https://github.com/tikv/pd/issues/5318

### What is changed and how does it work?

```commit-message
```

### Check List

Tests

- Unit test

### Release note

```release-note
Fix the issue that the statistics of the region tree may be not accurate
```

### CODE REVIEW

**Review by lhy1024 — APPROVED** [review]

**Review by lhy1024 — COMMENTED** [review]
Do we need to cherry-pick it to other branches?

**Comment by rleungx** [comment]
> Do we need to cherry-pick it to other branches?

I think we need and I will add a unit test later.

**Review by CabinfeverB — APPROVED** [review]

**Comment by CabinfeverB** [comment]
> Test modified, PTAL @lhy1024 @CabinfeverB

LGTM

**Review by lhy1024 — APPROVED** [review]

**Comment by nolouch** [comment]
cc @HunDunDM

**Review by HunDunDM — APPROVED** [review]

**Pull request merged**
