### PR TITLE
scatter: support group level scattering for regions (#2849)

### PR DESCRIPTION
**Pull request by ti-srebot**
cherry-pick #2849 to release-4.0

---

Signed-off-by: Song Gao <disxiaofei@163.com>

### What problem does this PR solve?

Resolve https://github.com/tikv/pd/issues/2732

### What is changed and how it works?

Add group parameter for the Scatter Region. If the group is defined, the regions with the same group would be scattered in the group level. This would be quite helpful If there are 2 `split table` running at the same time as the `tableID` would become the group for the regions in this case.

### Check List

Tests

- Unit test (simulate the concurrency visiting by regions in different groups.)

Related changes

- Need to cherry-pick to the release branch

### CODE REVIEW

**Review by lhy1024 — COMMENTED** [review]
plz fix conflict

**Review by lhy1024 — APPROVED** [review]

**Review by nolouch — COMMENTED** [review]
LGTM

**Pull request merged**
