### PR TITLE
Update the errors and tiup repositories to the latest version

### PR DESCRIPTION
**Pull request by lonng**
Signed-off-by: Lonng <heng@lonng.org>

### What problem does this PR solve?

Update the errors and TiUP to the latest version to make the error documentation work well. The PR pingcap/tiup#867 introduces functions that will merge the workaround/description from errors.toml with the error message from the repository. Make sure there are no conflicts between code and error metafile, the PR pingcap/errors#31 remove workaround/description options.

### Check List

Tests

- No code

### Release note

None

### CODE REVIEW

**Comment by JmPotato** [comment]
```shell
Files errors.toml and errors.toml.before differ
```

Please fix this first, thx.

**Review by rleungx — APPROVED** [review]

**Pull request merged**
