### PR TITLE
*: unify error handling by removing pkg/errors (#2644)

### LINKED ISSUE #2643: Unify the error handling by removing pkg/errors
Currently, the repo has three kinds of packages to handle errors. See `go.mod`.
```
github.com/pingcap/errcode v0.0.0-20180921232412-a1a7271709d9
github.com/pingcap/errors v0.11.5-0.20190809092503-95897b64e011
github.com/pkg/errors v0.9.1
```
It's better to replace `github.com/pkg/errors` with `github.com/pingcap/errors` since they are almost the same except for some fixes and stack support.

### PR DESCRIPTION
**Pull request by ti-srebot**
cherry-pick #2644 to release-4.0

---

### What problem does this PR solve?

Close #2643.

### What is changed and how it works?

This PR replaces `pkg/errors` with `pingcap/errors`.

### Check List

Tests

- Unit test

### CODE REVIEW

**Comment by lhy1024** [comment]
we need to fix conflict

**Review by lhy1024 — APPROVED** [review]

**Review by JmPotato — APPROVED** [review]
LGTM

**Pull request merged**
