### PR TITLE
server: fix goroutine leak in allocatorLeaderLoop

### PR DESCRIPTION
**Pull request by Yisaer**
Signed-off-by: Song Gao <disxiaofei@163.com>

### What problem does this PR solve?
Revising the defer `Stop` in order to avoid goroutine leak.

### Check List

Tests

### CODE REVIEW

**Comment by JmPotato** [comment]
I think this cloud be fixed by [#3267/longSleep](https://github.com/tikv/pd/pull/3267/files#diff-0d818fb56aef7677c53762dd2a46dd116a8e91979d743e3bee39cfa1dbc0bb3bR407)

**Review by lhy1024 — APPROVED** [review]

**Review by HunDunDM — APPROVED** [review]

**Comment by Yisaer** [comment]
/https://docs.google.com/document/d/1emQUIJ_ayczFCWNvVVgzdGY8n6LSyE7fDC5tXb5ZjmI/edit

**Pull request merged**
