### PR TITLE
operator: add send snapshot cost influence 

### LINKED ISSUE #5531: operator influence add snapshot send cost

### PR DESCRIPTION
**Pull request by bufferflies**
Signed-off-by: bufferflies <1045931706@qq.com>

### What problem does this PR solve?

Issue Number: Close  #5531

### What is changed and how does it work?
record the snapshot's sender cost.

```commit-message
```

### Check List

Tests

- Unit test

Code changes

Side effects

Related changes

### Release note

```release-note
 None.
```

### CODE REVIEW

**Review by rleungx — COMMENTED** [review]
How about adding some tests? The rest LGTM.

**Comment by bufferflies** [comment]
> How about adding some tests? The rest LGTM.

done

**Review by rleungx — APPROVED** [review]

**Review by CabinfeverB — APPROVED** [review]

**Pull request merged**
