### PR TITLE
Add force option to "pd-ctl store delete" command

### LINKED ISSUE #8878: Add force option to pd-ctl store delete
## Enhancement Task
There is no way to specify `force` in pd-ctl.
https://download.pingcap.com/pd-api-doc.html#store__storeid__delete

This option is useful in case of node failure, etc.
https://ask.pingcap.com/t/removing-a-completely-offline-tikv-node-from-the-cluster/4318/7

### PR DESCRIPTION
**Pull request by shunki-fujita**
### What problem does this PR solve?

Issue Number: Close #8878

### What is changed and how does it work?

Add `--force` option to `pd-ctl store delete` command.
Set status to Tombstone directly.
https://download.pingcap.com/pd-api-doc.html#store__storeid__delete

```commit-message
$ ./bin/pd-ctl store delete --help
delete the store

Usage:
  pd-ctl store delete <store_id> [flags]
  pd-ctl store delete [command]

Available Commands:
  addr        delete store by its address

Flags:
  -f, --force   Set status to Tombstone directly
  -h, --help    help for delete

Global Flags:
      --cacert string   path of file that contains list of trusted SSL CAs
      --cert string     path of file that contains X509 certificate in PEM format
      --key string      path of file that contains X509 key in PEM format
  -u, --pd string       address of PD (default "http://127.0.0.1:2379")

Use "pd-ctl store delete [command] --help" for more information about a command.
$
```

### Check List

Tests

- Unit test
- Integration test
- Manual test (add detailed scripts or steps below)
- No code

Code changes

- Has the configuration change
- Has HTTP API interfaces changed (Don't forget to [add the declarative for the new API](https://github.com/tikv/pd/blob/master/docs/development.md#updating-api-documentation))
- Has persistent data change

Side effects

- Possible performance regression
- Increased code complexity
- Breaking backward compatibility

Related changes

- PR to update [`pingcap/docs`](https://github.com/pingcap/docs)/[`pingcap/docs-cn`](https://github.com/pingcap/docs-cn):
- PR to update [`pingcap/tiup`](https://github.com/pingcap/tiup):
- Need to cherry-pick to the release branch

### Release note

```release-note
None.
```

### CODE REVIEW

**Comment by rleungx** [comment]
@shunki-fujita Thanks for your PR. But we have encountered many issues that misuse this API, so we prevent doing that anymore, see https://github.com/tikv/pd/issues/4039.

**Comment by shunki-fujita** [comment]
@rleungx 
Thank you for your reply!

The `--force` option sets `physical_destroyed=true` rather than directly setting store state to `Tombstone`.
https://github.com/tikv/pd/pull/3388

Even so, is it better not to implement this option?

(By the way, since it is not directly set to Tombstone, the help message might not be accurate.)
https://download.pingcap.com/pd-api-doc.html#store__storeid__delete

**Comment by rleungx** [comment]
> better

The reason why we use `physical_destroyed` is that we might need to add the store with the same address back in some scenarios, e.g., such as k8s env and we are sure that the previous store will never come back. `physical_destroyed` will let us no need to wait the damaged store finish offline before adding it's replacement. 
As for API docs, I believe that it's outdated. Let me fix it.

**Comment by rleungx** [comment]
> Thank you for your reply!
The --force option sets physical_destroyed=true rather than directly setting store state to Tombstone.
https://github.com/tikv/pd/pull/3388
Even so, is it better not to implement this option?
(By the way, since it is not directly set to Tombstone, the help message might not be correct.)
https://download.pingcap.com/pd-api-doc.html#store__storeid__delete> 

The reason why we use `physical_destroyed` is that we might need to add the store with the same address back in some scenarios, e.g., such as k8s env and we are sure that the previous store will never come back. `physical_destroyed` will let us no need to wait the damaged store finish offline before adding it's replacement. As for API docs, I believe that it's outdated. Let me fix it.

**Comment by shunki-fujita** [comment]
@rleungx 
> The reason why we use physical_destroyed is that we might need to add the store with the same address back in some scenarios, e.g., such as k8s env and we are sure that the previous store will never come back. physical_destroyed will let us no need to wait the damaged store finish offline before adding it's replacement. 

I encountered exactly that scenario, so I created this PR.
If implementing it in `pd-ctl` is considered risky, I will execute it via the API instead.

**Comment by rleungx** [comment]
Both pd-ctl command and api are dangrous. If you use force option, it will set the store state to offline, and it won't block you to add a replacement node. 

Here is an example:
if the damaged store id is 5 which **never come back including the data**. When calling the API with force option equal to true, the store 5 will be offline state. At this moment, you can add a replacement node, assume that the new store id is 6. 
We might have two stores with the same address but different id in the cluster. After the store 5 finish offline, it will become tombstone state.

**Comment by shunki-fujita** [comment]
@rleungx
Thank you for the advice.

> If the store 5 cannot be tombstone, it might have some other issues which we need to fix it instead of directly setting it to tombstone state.

I see,
I will conduct a verification separately.

**Pull request closed without merging**
