### PR TITLE
test/server: replace default 30s to 1s to reduce test cost time

### PR DESCRIPTION
**Pull request by HuSharp**
### What problem does this PR solve?

Issue Number: Ref #7969

### What is changed and how does it work?

rely on `net/http/pprof/pprof.go`

```
func Profile(w http.ResponseWriter, r *http.Request) {
	w.Header().Set("X-Content-Type-Options", "nosniff")
	sec, err := strconv.ParseInt(r.FormValue("seconds"), 10, 64)
	if sec <= 0 || err != nil {
		sec = 30
	}
```
reduce 30s to 1s

```commit-message
```

### Check List

Tests

- Integration test

### Release note

```release-note
None.
```

### CODE REVIEW

**Review by rleungx — APPROVED** [review]

**Review by nolouch — APPROVED** [review]

**Comment by HuSharp** [comment]
/hold
need to check why this code can pass in ci environment
https://github.com/tikv/pd/blob/63a61e9db8bc6c8405d99f06e6dc48341cc5af40/tests/server/api/api_test.go#L185

**Comment by HuSharp** [comment]
> /hold need to check why this code can pass in ci environment
> 
> https://github.com/tikv/pd/blob/63a61e9db8bc6c8405d99f06e6dc48341cc5af40/tests/server/api/api_test.go#L185

because TestRequestInfoMiddleware run after TestRateLimitMiddleware, which set 

https://github.com/tikv/pd/blob/5a7f1750dbef121e4f7fc45c8ccd311dc269a3fa/tests/server/api/api_test.go#L173-L175

which cannot pass failpoint in TestRequestInfoMiddleware

https://github.com/tikv/pd/blob/cf718a799fcddda5413e6e8c8df0a14270b3d20e/server/api/middleware.go#L58-L77

**Pull request merged**
