### PR TITLE
log: use the concurrently safe log to prevent the data race

### LINKED ISSUE #3159: Data Race of the log in allocatorLeaderLoop
## Bug Report
```
==================
WARNING: DATA RACE
Read at 0x000004568980 by goroutine 448:
  github.com/pingcap/log.Info()
      /home/ryan/go/pkg/mod/github.com/pingcap/log@v0.0.0-20200511115504-543df19646ad/global.go:30 +0x3e
  github.com/tikv/pd/server/tso.(*AllocatorManager).allocatorLeaderLoop()
      /home/ryan/pd/server/tso/allocator_manager.go:225 +0x186d

Previous write at 0x000004568980 by goroutine 234:
  github.com/pingcap/log.ReplaceGlobals()
      /home/ryan/go/pkg/mod/github.com/pingcap/log@v0.0.0-20200511115504-543df19646ad/log.go:110 +0x98
  github.com/tikv/pd/server.NewTestSingleConfig.func1()
      /home/ryan/pd/server/testutil.go:88 +0x77
  sync.(*Once).doSlow()
      /usr/local/go/src/sync/once.go:66 +0x109
  sync.(*Once).Do()
      /usr/local/go/src/sync/once.go:57 +0x68
  github.com/tikv/pd/server.NewTestSingleConfig()
      /home/ryan/pd/server/testutil.go:87 +0x58a
  github.com/tikv/pd/server.NewTestServer()
      /home/ryan/pd/server/testutil.go:42 +0xa4
  github.com/tikv/pd/tests/client_test.(*testClientSuite).SetUpSuite()
      /home/ryan/pd/tests/client/client_test.go:404 +0x55
  runtime.call32()
      /usr/local/go/src/runtime/asm_amd64.s:540 +0x3d
  reflect.Value.Call()
      /usr/local/go/src/reflect/value.go:336 +0xd8
  github.com/pingcap/check.(*suiteRunner).runFixture.func1()
      /home/ryan/go/pkg/mod/github.com/pingcap/check@v0.0.0-20200212061837-5e12011dc712/check.go:799 +0x1d0
  github.com/pingcap/check.(*suiteRunner).forkCall.func1()
      /home/ryan/go/pkg/mod/github.com/pingcap/check@v0.0.0-20200212061837-5e12011dc712/check.go:739 +0x121

Goroutine 448 (running) created at:
  github.com/tikv/pd/server/tso.(*AllocatorManager).SetUpAllocator()
      /home/ryan/pd/server/tso/allocator_manager.go:207 +0x710
  github.com/tikv/pd/server/tso.(*AllocatorManager).allocatorPatroller()
      /home/ryan/pd/server/tso/allocator_manager.go:408 +0x5b1
  github.com/tikv/pd/server/tso.(*AllocatorManager).AllocatorDaemon()
      /home/ryan/pd/server/tso/allocator_manager.go:352 +0x3a4
  github.com/tikv/pd/server.(*Server).tsoAllocatorLoop()
      /home/ryan/pd/server/server.go:529 +0x184

Goroutine 234 (running) created at:
  github.com/pingcap/check.(*suiteRunner).forkCall()
      /home/ryan/go/pkg/mod/github.com/pingcap/check@v0.0.0-20200212061837-5e12011dc712/check.go:734 +0x4cc
  github.com/pingcap/check.(*suiteRunner).runFunc()
      /home/ryan/go/pkg/mod/github.com/pingcap/check@v0.0.0-20200212061837-5e12011dc712/check.go:751 +0x84
  github.com/pingcap/check.(*suiteRunner).runFixture()
      /home/ryan/go/pkg/mod/github.com/pingcap/check@v0.0.0-20200212061837-5e12011dc712/check.go:795 +0x3d
  github.com/pingcap/check.(*suiteRunner).run()
      /home/ryan/go/pkg/mod/github.com/pingcap/check@v0.0.0-20200212061837-5e12011dc712/check.go:695 +0x12c
  github.com/pingcap/check.Run()
      /home/ryan/go/pkg/mod/github.com/pingcap/check@v0.0.0-20200212061837-5e12011dc712/run.go:150 +0x5a
  github.com/pingcap/check.RunAll()
      /home/ryan/go/pkg/mod/github.com/pingcap/check@v0.0.0-20200212061837-5e12011dc712/run.go:113 +0xf6e
  github.com/pingcap/check.TestingT()
      /home/ryan/go/pkg/mod/github.com/pingcap/check@v0.0.0-20200212061837-5e12011dc712/run.go:99 +0x736
  github.com/tikv/pd/tests/client_test.Test()
      /home/ryan/pd/tests/client/client_test.go:43 +0x38
  testing.tRunner()
      /usr/local/go/src/testing/testing.go:1127 +0x202
==================
```

### PR DESCRIPTION
**Pull request by JmPotato**
Signed-off-by: JmPotato <ghzpotato@gmail.com>

### What problem does this PR solve?

Try to resolve #3159. Related PR: pingcap/log#12.

### What is changed and how it works?

Use the concurrently safe log to prevent the data race.

### Check List

Tests

- Unit test
- Integration test

### CODE REVIEW

**Comment by rleungx** [comment]
IMO, these logs can help us investigate the problem.

**Comment by JmPotato** [comment]
> IMO, these logs can help us investigate the problem.

These logs will only be printed when the server is shut down. So I don't think these logs are providing us with more information.

**Comment by rleungx** [comment]
> > IMO, these logs can help us investigate the problem.
> 
> These logs will only be printed when the server is shut down. So I don't think these logs are providing us with more information.

It will help us to know whether this goroutine exits successfully.

**Comment by Yisaer** [comment]
> > > IMO, these logs can help us investigate the problem.
> > 
> > 
> > These logs will only be printed when the server is shut down. So I don't think these logs are providing us with more information.
> 
> It will help us to know whether this goroutine exits successfully.

I think it's unnecessary. If the goroutines didn't exit successfully. I think the `go test -tag leak` would expose this problem.

**Comment by lhy1024** [comment]
LGTM

**Review by lhy1024 — APPROVED** [review]

**Review by Yisaer — COMMENTED** [review]
LGTM @rleungx  PTAL

**Review by Yisaer — COMMENTED** [review]
LGTM

**Comment by JmPotato** [comment]
@rleungx @Yisaer I changed the way to fix this problem. PTAL.

**Review by nolouch — COMMENTED** [review]
/merge

**Comment by HunDunDM** [comment]
The race is caused by the test code, but the PR seems to degrade the code performance, please pay attention.
Now `log.Debug` also needs an atomic.

**Pull request merged**
