### PR TITLE
mcs: fix panic when getting the member which is not started

### LINKED ISSUE #7539: Panic when getting the member which is not started
## Bug Report

```
2023-12-13T07:34:21.9407031Z [2023/12/13 07:33:57.849 +00:00] [FATAL] [log.go:87] [panic] [recover={}] [stack="github.com/tikv/pd/pkg/utils/logutil.LogPanic\n\t/home/runner/work/pd/pd/pkg/utils/logutil/log.go:87\nruntime.gopanic\n\t/opt/hostedtoolcache/go/1.21.4/x64/src/runtime/panic.go:920\nruntime.goPanicIndex\n\t/opt/hostedtoolcache/go/1.21.4/x64/src/runtime/panic.go:114\ngithub.com/tikv/pd/pkg/mcs/scheduling/server.(*Server).updateAPIServerMemberLoop\n\t/home/runner/work/pd/pd/pkg/mcs/scheduling/server/server.go:195"]
2023-12-13T07:34:21.9407544Z FAIL	github.com/tikv/pd/tests/integrations/mcs/scheduling	50.414s
```

More details can be found in https://github.com/tikv/pd/actions/runs/7192072471/job/19588043944?pr=7538

### PR DESCRIPTION
**Pull request by rleungx**
### What problem does this PR solve?

Issue Number: Close #7539.

### What is changed and how does it work?

```commit-message
```

### Check List

Tests

- Unit test

### Release note

```release-note
None.
```

### CODE REVIEW

**Review by lhy1024 — APPROVED** [review]

**Review by CabinfeverB — APPROVED** [review]

**Comment by rleungx** [comment]
Merge it since there are two approvals. The label is only LGT1 due to some bug.

**Pull request merged**
