### PR TITLE
metrics: optimize the store state filter metrics (#2946)

### LINKED ISSUE #2933: Improve the metrics of store state filter
We have some metrics to help us locate the reason why the scheduling source or target is filtered. e.g.

Screen Shot 2020-09-09 at 11 01 37 AM

There is an item named *-store-state-filter which contains many situations, but we cannot distinguish them through the monitor directly. 

The logic of the store state filter can be found in https://github.com/tikv/pd/blob/master/server/schedule/filter/filters.go#L220-L358, The metrics related logic can be found in https://github.com/tikv/pd/blob/master/server/schedule/filter/filters.go#L66-L90

### PR DESCRIPTION
**Pull request by ti-srebot**
cherry-pick #2946 to release-4.0

---

### What problem does this PR solve?

Close #2933.

### What is changed and how it works?

This PR records the detailed reason in the filter type. After this PR:
Screen Shot 2020-09-14 at 2 25 07 PM

### Check List

Tests

- Manual test

### CODE REVIEW

**Comment by disksing** [comment]
It looks like this cherry-pick comes with many other commits (some of them may include behaviour changes).

**Review by lhy1024 — APPROVED** [review]

**Review by nolouch — APPROVED** [review]

**Review by nolouch — APPROVED** [review]

**Review by HunDunDM — APPROVED** [review]

**Pull request merged**
