### PR TITLE
pkg, server: remove the component manager pkg

### PR DESCRIPTION
**Pull request by JmPotato**
Signed-off-by: JmPotato <ghzpotato@gmail.com>

### What problem does this PR solve?

Ref https://github.com/tikv/tikv/issues/11472, https://github.com/tikv/pd/issues/4397. The component pkg has been deprecated. Since it is no longer used, I think we can remove it completely.

### Check List

Tests

- Unit test
- Integration test

### Release note

```release-note
None.
```

### CODE REVIEW

**Comment by rleungx** [comment]
IMO, it's better to remove it when we release the next major version/

**Review by nolouch — APPROVED** [review]
lgtm

**Review by lhy1024 — APPROVED** [review]

**Review by HunDunDM — APPROVED** [review]

**Review by rleungx — APPROVED** [review]

**Pull request merged**
