### PR TITLE
client: fix the block channel introduced by checkStreamTimeout

### PR DESCRIPTION
**Pull request by rleungx**
### What problem does this PR solve?

```
goroutine 270 [chan send, 2175 minutes]:
github.com/tikv/pd/client.(*client).tsLoop(0xc00070ede0)
	/home/jenkins/agent/workspace/tidb_v4.0.7/go/pkg/mod/github.com/tikv/pd@v1.1.0-beta.0.20200921100508-9ee41c4144f3/client/client.go:263 +0xda7
created by github.com/tikv/pd/client.NewClientWithContext
	/home/jenkins/agent/workspace/tidb_v4.0.7/go/pkg/mod/github.com/tikv/pd@v1.1.0-beta.0.20200921100508-9ee41c4144f3/client/client.go:178 +0x351
```
When the client timeout, the context will be canceled. And then `checkStreamTimeout` will return. But if at the same time the stream return with non-nil value. The `createdCh` will block.

### What is changed and how it works?

This PR fixes this problem by not allowing the checkStreamTimeout to return in advance.

### Check List

Tests

- Unit test

### Release note

- Fix the block channel introduced by checkStreamTimeout

### CODE REVIEW

**Review by JmPotato — APPROVED** [review]

**Review by crazycs520 — COMMENTED** [review]
LGTM

**Review by nolouch — COMMENTED** [review]
lgtm

**Review by nolouch — APPROVED** [review]
approve comment

**Pull request merged**
