### PR TITLE
metrics: make counter inc when operator finished rather than operator add (#2962)

### PR DESCRIPTION
**Pull request by ti-srebot**
cherry-pick #2962 to release-4.0

---

Signed-off-by: lhy1024 <admin@liudos.us>

### What problem does this PR solve?

we statistic the operator when the operator added, it will be more helpful to statistic `move-peer` and `move-leader` when the operator finished

### What is changed and how it works?

add additional counters

### Check List

Tests

- Unit test

### Release note

- improvement:  make counter inc when operator finished rather than operator add

### CODE REVIEW

**Comment by disksing** [comment]
Please resolve conflicts. @lhy1024

**Review by HunDunDM — APPROVED** [review]
LGTM

**Review by lhy1024 — APPROVED** [review]

**Pull request merged**
