### PR TITLE
*: update sysutil in go.mod to fix panic when search log

### LINKED ISSUE #4440: panic in search log
### What did you do?

related issue: https://github.com/pingcap/tidb/issues/27795

### PR DESCRIPTION
**Pull request by crazycs520**
Signed-off-by: crazycs <chen.two.cs@gmail.com>

### What problem does this PR solve?

close #4440

update `sysutil` in `go.mod` to fix panic when search log.

related PR: https://github.com/pingcap/sysutil/pull/33

### Check List

Tests

- Unit test

Code changes

- N/A

Side effects

- N/A

Related changes

- N/A

### Release note

```release-note
None
```

### CODE REVIEW

**Comment by crazycs520** [comment]
@nolouch @HunDunDM PTAL

**Review by JmPotato — APPROVED** [review]
LGTM. Please address the commit message.

**Review by rleungx — APPROVED** [review]

**Review by lonng — APPROVED** [review]
/lgtm

**Comment by rleungx** [comment]
Please change the commit message according to https://github.com/tikv/pd/blob/master/CONTRIBUTING.md#format-of-the-commit-message

**Pull request merged**
