### PR TITLE
filter: replace fmt.Sprint with strconv.parseUint64

### PR DESCRIPTION
**Pull request by bufferflies**
Signed-off-by: bufferflies <1045931706@qq.com>

### What problem does this PR solve?
related #3744， repalce fmt.Sprintf  with strconv.ParseUint to imporve filter performance . 

image

### What is changed and how it works?
some itoa  test: https://gist.github.com/evalphobia/caee1602969a640a4530
### Check List

Tests

- bench test

Code changes

Side effects

Related changes

### Release note

```release-note
replace fmt.Sprint with strconv.parseUint64
```

### CODE REVIEW

**Review by disksing — APPROVED** [review]

**Comment by rleungx** [comment]
There are some other codes using `Sprintf` too and how about replacing them all?

**Comment by bufferflies** [comment]
> There are some other codes using `Sprintf` too and how about replacing them all?

yes, there are some reference `Sprintf` in  other codes, it will be solved all in uncorrelated  issue.

**Review by rleungx — APPROVED** [review]

**Pull request merged**
