### PR TITLE
scheduler: fix pending influence collect

### LINKED ISSUE #5489: scheduler: unstable redundant schedule in hot scheduler
### What did you do?

run oltp point select workload in a three-node cluster

### What did you expect to see?

stable schedule

### What did you see instead?
image

### What version of PD are you using (`pd-server -V`)?
master

### PR DESCRIPTION
**Pull request by lhy1024**
Signed-off-by: lhy1024 <admin@liudos.us>

### What problem does this PR solve?

Issue Number: Close #5489

### What is changed and how does it work?

replace `cur.load` with `best.load` in pending influence

### Check List

Tests

- Unit test
- Integration test
- Manual test (add detailed scripts or steps below)

Before this pr
image
After this pr
image

### Release note

```release-note
None.
```

### CODE REVIEW

**Review by nolouch — COMMENTED** [review]
need some test

**Review by HunDunDM — APPROVED** [review]

**Review by nolouch — APPROVED** [review]

**Pull request merged**
