### PR TITLE
Add deepsource analyze

### PR DESCRIPTION
**Pull request by zhouqiang-cl**
Signed-off-by: Qiang Zhou <zhouqiang.cl@gmail.com>

### Check List

Tests

- Unit test
- Integration test
- Manual test (add detailed scripts or steps below)
- No code

Code changes

- Has configuration change
- Has HTTP API interfaces change (Don't forget to [add the declarative for API](https://github.com/tikv/pd/blob/master/docs/development.md#updating-api-documentation))
- Has persistent data change

Side effects

- Possible performance regression
- Increased code complexity
- Breaking backward compatibility

Related changes

- PR to update [`pingcap/docs`](https://github.com/pingcap/docs)/[`pingcap/docs-cn`](https://github.com/pingcap/docs-cn):
- PR to update [`pingcap/tidb-ansible`](https://github.com/pingcap/tidb-ansible):
- Need to cherry-pick to the release branch

### Release note

- No release note

### CODE REVIEW

**Review by nolouch — APPROVED** [review]

**Review by rleungx — APPROVED** [review]

**Comment by HunDunDM** [comment]
Please update the description.

**Pull request merged**
