### PR TITLE
server: fix the problem that get tso cannot work well in network partition environment

### PR DESCRIPTION
**Pull request by rleungx**
### What problem does this PR solve?

TiKV will get TSO in a fixed interval, while it cannot work well when the network partition happens. This is because after sending the request to the forwarding stream, it will continue to handle the next request. But TiKV uses this streaming method in a unary way, the next request will be EOF which will cancel the forwarding mechanism.

Closes https://github.com/tikv/pd/issues/3500

### What is changed and how it works?
This PR changes the way to handle forwarding TSO requests to avoid handling the next request before the forwarding stream responds.

### Check List

Tests

- Manual test

Related changes

- Need to cherry-pick to the release branch

### Release note

- Fix the problem that get TSO cannot work well in a network partition environment

### CODE REVIEW

**Review by JmPotato — COMMENTED** [review]
I think we should add a TODO to mark we should update this part of logic after TiKV uses the stream way to get TSO. Rest LGTM.

**Review by nolouch — APPROVED** [review]
lgtm

**Review by JmPotato — APPROVED** [review]

**Pull request merged**
