### PR TITLE
dashboard: Update TiDB Dashboard to v2021.06.15.1 (#3785)

### PR DESCRIPTION
**Pull request by shhdgit**
### What problem does this PR solve?

This is an cherry-pick of #3785

Signed-off-by: Suhaha jklopsdfw@gmail.com

### Check List

Update to TiDB Dashboard v2021.06.15.1

Tests

- Manual test (add detailed scripts or steps below)

Related changes

- Need to cherry-pick to the release branch

### Release note

```release-note
Update TiDB Dashboard to v2021.06.15.1
```

### CODE REVIEW

**Comment by rleungx** [comment]
Hi, seems it is duplicated with #3794.

**Comment by shhdgit** [comment]
Yes, how do I resolve the conflict in #3794, instead of opening a new pr?

**Comment by breeswish** [comment]
@nolouch Please take a look about this PR, and please help close these two, thanks!

https://github.com/tikv/pd/pull/3794
https://github.com/tikv/pd/pull/3793

**Comment by HunDunDM** [comment]
> Yes, how do I resolve the conflict in #3794, instead of opening a new pr?

Due to some security issues, we are temporarily unable to do so, I will close the bot PR.

**Review by HunDunDM — APPROVED** [review]

**Comment by shhdgit** [comment]
Thank you so much.

**Review by nolouch — APPROVED** [review]

**Pull request merged**
