### PR TITLE
metrics: remove scheduler event monitor

### LINKED ISSUE #5396: Remove balance event in the monitor
## Enhancement Task
We have a row named balance region/leader event in the monitor right now:
Screen Shot 2022-08-03 at 7 31 27 PM
IMO, it doesn't provide any valid information and some metrics are duplicated with movement. We can remove it completely.

### PR DESCRIPTION
**Pull request by rleungx**
Signed-off-by: Ryan Leung <rleungx@gmail.com>

### What problem does this PR solve?

Issue Number: Close #5396.
### What is changed and how does it work?

```commit-message
```

### Check List

Tests

- Manual test

### Release note

```release-note
None
```

### CODE REVIEW

**Comment by rleungx** [comment]
Now, it looks good. @bufferflies PTAL.

**Review by bufferflies — APPROVED** [review]

**Review by nolouch — APPROVED** [review]

**Pull request merged**
