### PR TITLE
mcs: make compatible with cluster info page display

### LINKED ISSUE #7928: Dashboard cluster info page raise not support micro service error
### What did you do?

vucUtNbRsL

### What version of PD are you using (`pd-server -V`)?
Release Version: v8.0.0-alpha
Edition: Community
Git Commit Hash: da97f9c889f640ea334e795b5381592e4d290fde
Git Branch: heads/refs/tags/v8.0.0-alpha
UTC Build Time:  2024-03-15 11:36:59

### PR DESCRIPTION
**Pull request by lhy1024**
### What problem does this PR solve?

Issue Number: Close #7928

### What is changed and how does it work?

```commit-message
```

### Check List

Tests

- Unit test

### Release note

```release-note
None.
```

### CODE REVIEW

**Review by baurine — APPROVED** [review]

**Comment by lhy1024** [comment]
Before
image
After
image

**Review by HuSharp — APPROVED** [review]

**Review by CabinfeverB — APPROVED** [review]

**Pull request merged**
