### PR TITLE
grpc_service: add missing SplitAndScatterRegions method

### LINKED ISSUE #4345: implement the missing SplitAndScatterRegions method
## Development Task

I can't update kvproto for TiDB due to
```
# github.com/tikv/pd/server
../../go/pkg/mod/github.com/tikv/pd@v1.1.0-beta.0.20211029083450-e65f0c55b6ae/server/server.go:254:24: cannot use s (type *Server) as type pdpb.PDServer in argument to pdpb.RegisterPDServer:
        *Server does not implement pdpb.PDServer (missing SplitAndScatterRegions method)
```

Let me implement the interface first.

### PR DESCRIPTION
**Pull request by youjiali1995**
### What problem does this PR solve?

Close #4345

### What is changed and how it works?

Copy some codes from https://github.com/tikv/pd/pull/4333 to implement the `SplitAndScatterRegions` interface. 

### Check List

Tests

- Manual test (add detailed scripts or steps below)

Build TiDB successfully.

Code changes

Side effects

Related changes

### Release note

```release-note
None
```

### CODE REVIEW

**Review by nolouch — APPROVED** [review]

**Review by disksing — APPROVED** [review]

**Review by lhy1024 — APPROVED** [review]

**Comment by nolouch** [comment]
there is unstable test, ref to https://github.com/tikv/pd/issues/4348

**Pull request merged**
