### PR TITLE
hot scheduler: remove unused code

### PR DESCRIPTION
**Pull request by disksing**
Signed-off-by: disksing <i@disksing.com>

### What is changed and how it works?
As `hotPeerFilterType` is always `mixed`, we can remove it.
`hotRegionThreshold` is only used when `hotPeerFilterType` is not `mixed` so we can remove it too.

Removed unused code to make it easier to read. We can add it back in the future if we want it again.

### Check List

Tests
- Unit test

### Release note
- No release note

### CODE REVIEW

**Comment by lhy1024** [comment]
Previously, we wanted to use this strategy but then gave up.

PTAL @rleungx  @nolouch

**Review by lhy1024 — APPROVED** [review]

**Review by HunDunDM — APPROVED** [review]

**Pull request merged**
