### PR TITLE
Update TiDB Dashboard to v2021.12.06.1 [master]

### PR DESCRIPTION
**Pull request by shhdgit**
Signed-off-by: Suhaha <jklopsdfw@gmail.com>

### What problem does this PR solve?

Update TiDB Dashboard to v2021.12.06.1 https://github.com/pingcap/tidb-dashboard/pull/1084

### What is changed and how it works?
fix: globally delete/update data by GORM https://github.com/pingcap/tidb-dashboard/pull/1065
fix: request header being pinned after pd profiling https://github.com/pingcap/tidb-dashboard/pull/1069

### Check List

Tests

- Manual test (add detailed scripts or steps below)

Side effects

Related changes

- Need to cherry-pick to the release branch: release-5.3

### Release note

```release-note
None
```

### CODE REVIEW

**Comment by rleungx** [comment]
Can you describe what is changed or add a link for v2021.12.06.1 in the PR description?

**Comment by shhdgit** [comment]
> Can you describe what is changed or add a link for v2021.12.06.1 in the PR description?

PTAL, thanks~

**Review by rleungx — APPROVED** [review]

**Review by JmPotato — APPROVED** [review]

**Pull request merged**
