### PR TITLE
ci: fix wrong boltdb dependency

### PR DESCRIPTION
**Pull request by nolouch**
Signed-off-by: nolouch <nolouch@gmail.com>

### What problem does this PR solve?
close https://github.com/tikv/pd/issues/4528
fix wrong `boltdb` dependency

### What is changed and how it works?
fix the go.mod
### Check List

Tests

- Unit test
- Integration test

### Release note

```release-note
None
```

### CODE REVIEW

**Review by HunDunDM — APPROVED** [review]

**Comment by HunDunDM** [comment]
ref #4502

**Review by lhy1024 — APPROVED** [review]

**Comment by nolouch** [comment]
test removed because useless, ref https://github.com/tikv/pd/pull/4532.

**Pull request merged**
