### PR TITLE
*: fix disable failpoint 

### PR DESCRIPTION
**Pull request by rleungx**
### What problem does this PR solve?

Issue Number: Ref #4399.

### What is changed and how does it work?

```commit-message
```

### Check List

Tests

- Unit test

### Release note

```release-note
None.
```

### CODE REVIEW

**Review by lhy1024 — APPROVED** [review]

**Review by nolouch — COMMENTED** [review]
Do you test it, is it improved?

**Review by binshi-bing — APPROVED** [review]
Where is the description of the issue? If there is description, shall we add one? 
Does it aim to fix the pd leader issue mentioned in on-call?

**Comment by rleungx** [comment]
> Do you test it, is it improved?

No, haven't tested yet. I will update the result once I finished it. But theoretically, we need to pass the context in this way.

**Comment by rleungx** [comment]
> Do you test it, is it improved?

Yes, but it seems there is no much difference for this case since TiKV doesn't use context.

**Pull request merged**
