### PR TITLE
server: return GetMembers error as a gRPC error to let TiKV retry

### LINKED ISSUE #5409: GetMembers error should return as a gRPC error to let TiKV retry
## Bug Report

Details: https://github.com/tikv/tikv/issues/13124.

We should return the gRPC error in some cases to let TiKV retry on the next PD member.

Ref: https://github.com/tikv/pd/pull/5310/files#diff-eb404b45d0a569b05f58f4e4bf2b42b32150be75ec2ed72f86330c4b5d739eabR108

### PR DESCRIPTION
**Pull request by JmPotato**
Signed-off-by: JmPotato <ghzpotato@gmail.com>

### What problem does this PR solve?

Issue Number: Ref #5309. Close #5409.

### What is changed and how does it work?

```commit-message
Return GetMembers error as a gRPC error to let TiKV retry.
```

### Check List

Tests

- Unit test
- Integration test

Related changes

https://github.com/tikv/pd/pull/5310.

### Release note

```release-note
None.
```

### CODE REVIEW

**Comment by JmPotato** [comment]
@HuSharp PTAL.

**Review by Connor1996 — APPROVED** [review]
LGTM

**Review by Connor1996 — COMMENTED** [review]
better walk through the other spots to make sure no wrong return. I check `AllocID` and `BootStrap`, they seems okay.

**Comment by JmPotato** [comment]
Close since

**Pull request closed without merging**
