### PR TITLE
client: avoid the potential PD client panic

### PR DESCRIPTION
**Pull request by JmPotato**
Signed-off-by: JmPotato <ghzpotato@gmail.com>

### What problem does this PR solve?

Some type assertions in the PD client are not safe. This PR fixs them.

### What is changed and how it works?

Make sure the `interface{}` is not nil before we do the type assertion.

### Check List

Tests

- Unit test
- Integration test

### CODE REVIEW

**Review by rleungx — COMMENTED** [review]
Would like to add a unit test?

**Review by nolouch — APPROVED** [review]
lgtm

**Review by Yisaer — APPROVED** [review]
LGTM

**Pull request merged**
