### PR TITLE
chore(dashboard): update tidb dashboard verstion to v2023.11.08.1

### PR DESCRIPTION
**Pull request by baurine**
### What problem does this PR solve?

Issue Number: Close https://github.com/tikv/pd/issues/7340

TiDB Dashboard release PR: https://github.com/pingcap/tidb-dashboard/pull/1611

### Release note

```release-note
1. Show `plan_cache_hits` field for statement
2. Support tikv heap profiling
```

## Test & Preview

```
tiup playground nightly --tiflash 0 --pd.binpath /mnt/bao/codes/work/pd/bin/pd-server
```

image

image

### CODE REVIEW

**Comment by baurine** [comment]
This PR needs to cherry-pick to release-7.5

**Review by Connor1996 — APPROVED** [review]
LGTM

**Review by rleungx — APPROVED** [review]

**Pull request merged**
