### PR TITLE
schedulers:  speed up the `balance-region-scheduler ` by decrease influence amp.

### LINKED ISSUE #4990: Balance region is too slow
### What did you do?

Scale out two TiKV.

### What did you expect to see?

Balance speed in a reasonable value

### What did you see instead?

Screen Shot 2022-05-19 at 11 42 24 AM
Screen Shot 2022-05-19 at 2 55 41 PM

But from the debug log:
```
[2022/05/19 14:42:34.465 +08:00] [DEBUG] [utils.go:126] ["skip balance region"] [scheduler=balance-region-scheduler] [region-id=7902] [source-store=2] [target-store=20341] [source-size=92339] [source-score=142775.35001723023] [source-influence=0] [target-size=46986] [target-score=5715141991.420612] [target-influence=90] [average-region-size=73] [tolerant-resource=0]
```
The target score is `5715141991.420612` which is not expected.

### What version of PD are you using (`pd-server -V`)?
master

### PR DESCRIPTION
**Pull request by bufferflies**
### What problem does this PR solve?

Issue Number: Close #4990

### What is changed and how does it work?

```commit-message
schedulers: speed up the balance-region-scheduler by decrease influence amp
```

### Check List

Tests

- Unit test
- Manual test (add detailed scripts or steps below)

##### current
operator:
image
region count:
image

##### master
image

##### current

image
region count:
image

##### master
image

Code changes

Side effects

Related changes

- Need to cherry-pick to the release branch

### Release note

```release-note
None.
```

### CODE REVIEW

**Review by lhy1024 — COMMENTED** [review]
Do we need more tests in the real cluster?

**Comment by bufferflies** [comment]
> ?

the 4 TIKV, 1GB region size is real cluster.

**Review by nolouch — COMMENTED** [review]
Could you show the the before behavior?

**Review by nolouch — APPROVED** [review]

**Comment by nolouch** [comment]
ptal @HunDunDM

**Review by lhy1024 — APPROVED** [review]

**Comment by nolouch** [comment]
@bufferflies  conflict.

**Pull request merged**
