### PR TITLE
chore(dashboard): update version to v2023.09.11.1

### LINKED ISSUE #7066: dashboard: improve dashboard login security, encrypt the login password
## Development Task

Related tidb-dashboard release: https://github.com/pingcap/tidb-dashboard/pull/1588

### PR DESCRIPTION
**Pull request by baurine**
### What problem does this PR solve?

Issue Number: Close #7066 

### What is changed and how does it work?

Related tidb-dashboard release: https://github.com/pingcap/tidb-dashboard/pull/1588

```commit-message
1. security: improve tidb-dashboard login security, encrypt the login password to avoid transport plain text (required for 6.5 version)
2. debug-api: support pagination for ddl history for debug-api
3. keyvisual: use scanRegions instead of fetch all regions (required for 6.5 version)
4. refine execution plan, now it can be showed as table style
```

### Release note

```release-note
None.
```

### Test

```
make pd-server
tiup playground v6.5.4 --tiflash 0 --pd.binpath /mnt/bao/codes/work/pd/bin/pd-server
```

image

### CODE REVIEW

**Comment by baurine** [comment]
This tidb-dashboard version includes the new feature about refined execution plan, and is promised to bring to 7.4, so this PR is need to cherry-pick to master branch. And it's nice to cherry-pick the LTS version (7.1, 6.1) as well (so #6997  and #6998 can be closed directly)

**Review by nolouch — APPROVED** [review]

**Pull request merged**
