### PR TITLE
server/schedule: priority to fit healthy peers

### LINKED ISSUE #4233: Priority to fit health peer with placement rules
### Describe your feature request related problem

After https://github.com/tikv/pd/pull/4075, it can solve the problem mentioned in https://github.com/tikv/pd/issues/4045. But here is a new problem：
- Suppose the current rule is 1 learner. and the region has 2 learners, one is a pending learner and the other is normal learner. When calculating region fit rules, the pending match may be fitted, the normal learner seen as an orphan. In this case, because of the constraints introduced by the above PR, no repairs will be made.

###  Describe your consider

Consider to Priority to fit health peer.

### Teachability, Documentation, Adoption, Migration Strategy

-GO

### PR DESCRIPTION
**Pull request by sunby**
### What problem does this PR solve?

fixes #4233 

### What is changed and how it works?

Adjust the peers order in `newFitWorker` to put healthy peers in front
### Check List

Tests

- Unit test

### Release note

```release-note
NONE
```

### CODE REVIEW

**Review by nolouch — APPROVED** [review]
Thanks, lgtm.

**Comment by nolouch** [comment]
PTAL @disksing

**Review by disksing — APPROVED** [review]

**Review by HunDunDM — APPROVED** [review]

**Comment by sunby** [comment]
The pr is out-of-date with master. Just rebase master and push again @nolouch

**Pull request merged**
