### PR TITLE
dashboard: Update TiDB Dashboard to v2021.06.15.1 (#3785)

### PR DESCRIPTION
**Pull request by shhdgit**
### What problem does this PR solve?

This is an cherry-pick of #3785

Signed-off-by: Suhaha jklopsdfw@gmail.com

### Check List

Update to TiDB Dashboard v2021.06.15.1

Tests

- Manual test (add detailed scripts or steps below)

Related changes

- Need to cherry-pick to the release branch

### Release note

```release-note
Update TiDB Dashboard to v2021.06.15.1
```

### CODE REVIEW

**Comment by breeswish** [comment]
@nolouch Please take a look, thanks!

And the label may need some fix.. It is not "need cherry pick", but "is a cherry pick".

**Comment by shhdgit** [comment]
Yes, but there's no "is a cherry pick" label. It would be better if the ti-chi robot gave me a pr invitation.

**Review by HunDunDM — APPROVED** [review]

**Review by nolouch — APPROVED** [review]

**Pull request merged**
