### PR TITLE
server/id: pre-alloc id gauge metrics

### PR DESCRIPTION
**Pull request by nolouch**
Signed-off-by: nolouch <nolouch@gmail.com>

### What problem does this PR solve?

Issue Number: Close https://github.com/tikv/pd/issues/4623

### What is changed and how it works?

```commit-message
server/id: pre-alloc id gauge metrics
```

### Check List

Tests

- Unit test

### Release note

```release-note
None
```

### CODE REVIEW

**Comment by disksing** [comment]
I think alloc id should be a low-frequency enough operation that it doesn't seem worth doing such an optimization.

**Review by lhy1024 — APPROVED** [review]

**Review by JmPotato — APPROVED** [review]
LGTM. But should this close the issue https://github.com/tikv/pd/issues/4623? The TSO part still needs to be addressed.

**Comment by nolouch** [comment]
@disksing Yes, Here is. I mainly want to remove the usage of `withLabelValues` in the key service packages. otherwise, it's may guide developers to use the same way.

**Pull request merged**
