### PR TITLE
go.mod: upgrade gin version from v1.8.1 to v1.9.1

### LINKED ISSUE #7438: Upgrade Gin Web Framework version to solve some security issues
## Bug Report

Gin Web Framework v1.8.1 has some security issues [Gin Security Issues](https://github.com/xiabee/pd-security-test/pull/2), we need to upgrade the version to v1.9.1

### PR DESCRIPTION
**Pull request by niubell**
### What problem does this PR solve?

Issue Number: Close #7438 

### What is changed and how does it work?

```commit-message
Upgrade Gin version to v1.9.1 to solve some security issues
```

### Check List

Tests

- Integration test
- Manual test (add detailed scripts or steps below)
- No code

Code changes

Side effects

Related changes

- Need to cherry-pick to the release branch

### Release note

```release-note
Upgrade Gin version to v1.9.1 to solve some security issues.
```

### CODE REVIEW

**Comment by rleungx** [comment]
Please sign-off DCO.

**Comment by niubell** [comment]
> there are many `go.mod` in pd, maybe need to update other `go.mod` as well

yes, I will fix those go.mod together

**Pull request closed without merging**
