### PR TITLE
metrics: fix the filter metrics (#3197)

### LINKED ISSUE #3195: Lose some metrics in both source and target filters
### What did you do?

The operator can not be created continuously and use filter metrics to help

### What did you expect to see?

The metrics can help figure out the reason.

### What did you see instead?

But there is no data point in both filter source/target.

### What version of PD are you using (`pd-server -V`)?
master (11.23)

### PR DESCRIPTION
**Pull request by ti-srebot**
cherry-pick #3197 to release-4.0

---

Signed-off-by: Ryan Leung <rleungx@gmail.com>

### What problem does this PR solve?

Close #3195.

### What is changed and how it works?

This PR fixes the filter source/target metrics.

### Check List

Tests

- Manual test

Related changes

- Need to cherry-pick to the release branch

### CODE REVIEW

**Review by nolouch — APPROVED** [review]
LGTM

**Review by lhy1024 — APPROVED** [review]

**Review by HunDunDM — APPROVED** [review]

**Comment by hi-rustin** [comment]
> @ti-srebot: Your PR has out-of-dated and I have automatically updated it for you.
> At the same time I will also trigger all tests for you:
> 
> /run-all-tests

@zhouqiang-cl  It seems bot can not trigger `idc-jenkins-ci-pd/integration-lightning-test` job.

cc: @nolouch

**Pull request merged**
