### PR TITLE
Revert "schedulers: fix check hot region flow (#3203)"

### PR DESCRIPTION
**Pull request by nolouch**
This reverts commit c2688375e6e5271fe1f958a000e73d1a2317464e.

### What problem does this PR solve?

We need more test with this PR, in my test, the hot region is 
### What is changed and how it works?
Under a random insert workload, a particularly large number of hotspot regions have been identified, resulting in more hotspot scheduling. We need to confirm whether this behavior is reasonable, so firstly revert this PR in the release branch.
image

### Check List

Tests

- Unit test
- Integration test
- Manual test (add detailed scripts or steps below)

### CODE REVIEW

**Review by HunDunDM — APPROVED** [review]

**Review by lhy1024 — APPROVED** [review]
So sad

**Pull request merged**
