### PR TITLE
statistics: use unbounded chan in hot task item queue

### LINKED ISSUE #5791: statistics: hot statistics queue block when pd-heartbeat-bench
### What did you do?

run pd-heartbeat-bench

### What did you expect to see?

no queue block

### What did you see instead?

image

### What version of PD are you using (`pd-server -V`)?

master

### PR DESCRIPTION
**Pull request by lhy1024**
Signed-off-by: lhy1024 <admin@liudos.us>

### What problem does this PR solve?

Issue Number: Close #5791

### What is changed and how does it work?

```commit-message
```

### Check List

Tests

- Unit test
- Integration test
image
image

### Release note

```release-note
None.
```

### CODE REVIEW

**Comment by rleungx** [comment]
Will it cause an unexpected memory increase when the cluster runs for a long time?

**Comment by lhy1024** [comment]
> Will it cause an unexpected memory increase when the cluster runs for a long time?

1. it will clear after chan empty, https://github.com/smallnest/chanx/blob/2c313971bc4b9d4a281ff311327fdfe1c71ce2c6/unbounded_chan.go#L108

2. it will only cost 180M memory in pd-heartbeat-bench with 2000000 region

**Review by HunDunDM — APPROVED** [review]

**Comment by nolouch** [comment]
Will it may cause oom?

**Review by nolouch — APPROVED** [review]

**Pull request merged**
