### PR TITLE
pkg: refactor the progress indicator

### PR DESCRIPTION
**Pull request by rleungx**
Signed-off-by: Ryan Leung <rleungx@gmail.com>

### What problem does this PR solve?

Issue Number: Ref #4640.

### What is changed and how does it work?

This PR is a part of #4718. Split it for easier reviewing.

```commit-message
```

### Check List

Tests

- Unit test

### Release note

```release-note
None
```

### CODE REVIEW

**Review by AndreMouche — COMMENTED** [review]
Rest LGTM

**Review by AndreMouche — APPROVED** [review]
LGTM

**Review by CabinfeverB — APPROVED** [review]

**Review by nolouch — APPROVED** [review]

**Pull request merged**
