### PR TITLE
*: upgrade go to 1.23

### LINKED ISSUE #8644: Upgrade go version to 1.23
## Enhancement Task
Go 1.23 is released! Release notes https://go.dev/doc/go1.23.

In order to be able to use some new features introduced in go1.23. We plan to upgrade go version to 1.23.1 on master branch( from version v8.4.0 use the go1.23).

### PR DESCRIPTION
**Pull request by rleungx**
### What problem does this PR solve?

Issue Number: Close #8644

### What is changed and how does it work?

```commit-message
```

### Check List

Tests

- Unit test

### Release note

```release-note
None.
```

### CODE REVIEW

**Comment by purelind** [comment]
/hold

Waiting for the test report to be completed.

**Review by lhy1024 — APPROVED** [review]

**Review by nolouch — APPROVED** [review]

**Pull request merged**
