### PR TITLE
placement: Remove ValidateRegion and ValidateStores from cache check

### LINKED ISSUE #5241: plancement/region_rule_cache: check ValidateRegion&ValidateStores are redundant and preformance  underfriendly
## Enhancement Task
It is unfriendly for performance and also redundant to check ValidDateRegion & ValidateStores in  the function `IsUnchanged`
[https://github.com/tikv/pd/blob/c8775b6176a03eb25cb1622fc46ba1d496872df7/server/schedule/placement/region_rule_cache.go#L93-L98](https://github.com/tikv/pd/blob/c8775b6176a03eb25cb1622fc46ba1d496872df7/server/schedule/placement/region_rule_cache.go#L93-L98)

since, firstly, the only caller of `IsUnchanged` was in `CheckAndGetCache`, it already checked in L61
[https://github.com/tikv/pd/blob/c8775b6176a03eb25cb1622fc46ba1d496872df7/server/schedule/placement/region_rule_cache.go#L58-L71](https://github.com/tikv/pd/blob/c8775b6176a03eb25cb1622fc46ba1d496872df7/server/schedule/placement/region_rule_cache.go#L58-L71)

secondly, L98 will validate it again since all regions into the cache should be validate first.

### PR DESCRIPTION
**Pull request by ihcsim**
### What problem does this PR solve?

This PR removes the redundant `ValidateRegion` and `ValidateStores` checks from the `cache.IsUnchanged()` method, per description in #5241.

Issue Number: Close #5241

### What is changed and how does it work?

```commit-message
```

### Check List

Tests

- Unit test

### Release note

```release-note
None
```

### CODE REVIEW

**Comment by nolouch** [comment]
PTAL @HunDunDM

**Review by lhy1024 — APPROVED** [review]
Would you like to add a bench result before and after this pr?

**Comment by ihcsim** [comment]
@lhy1024 yes, I can look into it. Can you re-run CI? I don't think the failure is related to my change. Thanks.

**Comment by lhy1024** [comment]
```
2022-11-28T11:48:42.3004909Z --- FAIL: TestRegionRuleFitCache (0.00s)
2022-11-28T11:48:42.3104432Z     region_rule_cache_test.go:179: unchanged
2022-11-28T11:48:42.3105097Z     region_rule_cache_test.go:179: leader changed
2022-11-28T11:48:42.3105660Z     region_rule_cache_test.go:179: have down peers
2022-11-28T11:48:42.3106078Z     region_rule_cache_test.go:180: 
2022-11-28T11:48:42.3149245Z         	Error Trace:	region_rule_cache_test.go:180
2022-11-28T11:48:42.3151950Z         	Error:      	Not equal: 
2022-11-28T11:48:42.3154620Z         	            	expected: false
2022-11-28T11:48:42.3157230Z         	            	actual  : true
2022-11-28T11:48:42.3159750Z         	Test:       	TestRegionRuleFitCache
```

**Comment by ihcsim** [comment]
Sorry for the delay. I was hoping to complete this after KubeCon NA, but I have been very busy since. I think I'm going to close this PR for now, until I have the time again. Thanks!

**Pull request closed without merging**
