### PR TITLE
election, member, tso: fix the leader check bug and refine the logic

### PR DESCRIPTION
**Pull request by JmPotato**
Signed-off-by: JmPotato <ghzpotato@gmail.com>

### What problem does this PR solve?

If you check the leader immediately after the campaign failed by `leadership.Check()`, it will return true wrongly because the lease is not expired yet. And to be more specific, this bug could cause a PD to make a non-leader Local TSO Allocator participate in a Global TSO synchronization, which will make the synchronization fail, right after the campaign failed. This PR will fix this problem.

Also, I rearrange the logic in `allocatorLeaderLoop` to reduce the RPC requests and etcd IO, which should improve the performance.

### What is changed and how it works?

* Merge `IsStillLeader` and `IsLeader` methods, they are doing the same thing.
* Improve the leader check to make it more precise.
* Rearrange the logic in `allocatorLeaderLoop` to reduce the RPC requests and etcd IO.

### Check List

Tests

- Unit test
- Integration test

### CODE REVIEW

**Review by nolouch — APPROVED** [review]
LGTM

**Review by Yisaer — APPROVED** [review]
LGTM

**Comment by rleungx** [comment]
Does this PR have any tests?

**Comment by JmPotato** [comment]
> Does this PR have any tests?

I add a test in this [PR](https://github.com/tikv/pd/pull/3290/files#diff-adc274c7b56e5c4c0238e59a97673d30cb885c99c4cf588eb194990772d323a1).

**Pull request merged**
