### PR TITLE
dr: speed up the dr ticker

### PR DESCRIPTION
**Pull request by nolouch**
Signed-off-by: nolouch <nolouch@gmail.com>

### What problem does this PR solve?

Issue Number: Close https://github.com/tikv/pd/issues/5512

### What is changed and how does it work?

```commit-message
dr: speed up the dr ticker
```

### Check List

Tests

- Unit test

### Release note

```release-note
None.
```

### CODE REVIEW

**Comment by lhy1024** [comment]
Will it make CPU costs increase?

**Comment by nolouch** [comment]
> Will it make CPU costs increase?
no, it checks 2 times every second. and no many calculate tasks.

**Review by lhy1024 — APPROVED** [review]

**Review by disksing — APPROVED** [review]

**Pull request merged**
