### PR TITLE
config: remove the configuration of store limit mode

### PR DESCRIPTION
**Pull request by bufferflies**
### What problem does this PR solve?

Issue Number: Ref #4399

### What is changed and how does it work?

```commit-message
 remove the configuration of store limit mode
```

### Check List

Tests

- Unit test

Code changes

- Has the configuration change

Side effects

- Breaking backward compatibility

Related changes

- PR to update [`pingcap/docs`](https://github.com/pingcap/docs)/[`pingcap/docs-cn`](https://github.com/pingcap/docs-cn):
- PR to update [`pingcap/tiup`](https://github.com/pingcap/tiup):
- Need to cherry-pick to the release branch

### Release note

```release-note
 remove the configuration of store limit mode
```

### CODE REVIEW

**Review by nolouch — COMMENTED** [review]
why remove it?

**Review by nolouch — COMMENTED** [review]
why remove it?

**Review by nolouch — COMMENTED** [review]
why remove it?

**Comment by bufferflies** [comment]
> why remove it?
1. the store limit mode does work iff user set it, and nobody use it in online cluster.
2. the store limit version can replace it well.

**Review by nolouch — APPROVED** [review]

**Pull request merged**
