### PR TITLE
api: fix /min-resolved-ts panic

### LINKED ISSUE #5247: pd panic when call /min-resolved-ts
### What did you do?
start 1 pd-server without tikv, then call `/min-resolved-ts` api

### What did you expect to see?
normal output
### What did you see instead?
panic
### What version of PD are you using (`pd-server -V`)?
master

### PR DESCRIPTION
**Pull request by D3Hunter**
### What problem does this PR solve?

Issue Number: Close #5247

### What is changed and how does it work?
- check cluster running before api call

```commit-message
```

### Check List

Tests

- Unit test
- Integration test
- Manual test (add detailed scripts or steps below)
- No code

Code changes

- Has configuration change
- Has HTTP API interfaces changed (Don't forget to [add the declarative for the new API](https://github.com/tikv/pd/blob/master/docs/development.md#updating-api-documentation))
- Has persistent data change

Side effects

- Possible performance regression
- Increased code complexity
- Breaking backward compatibility

Related changes

- PR to update [`pingcap/docs`](https://github.com/pingcap/docs)/[`pingcap/docs-cn`](https://github.com/pingcap/docs-cn):
- PR to update [`pingcap/tiup`](https://github.com/pingcap/tiup):
- Need to cherry-pick to the release branch

### Release note

```release-note
fix /min-resolved-ts panic
```

### CODE REVIEW

**Review by rleungx — APPROVED** [review]

**Comment by rleungx** [comment]
Please sign off DCO.

**Review by lhy1024 — APPROVED** [review]

**Comment by D3Hunter** [comment]
> Please sign off DCO.

done

**Pull request merged**
