### PR TITLE
*: remove applying snapshot count

### PR DESCRIPTION
**Pull request by rleungx**
Signed-off-by: Ryan Leung <rleungx@gmail.com>

### What problem does this PR solve?

The value is always zero and PD doesn't need to handle the corresponding logic anymore.

### What is changed and how it works?

Remove the apply snap count.

### Check List

Tests

- Unit test

### CODE REVIEW

**Comment by HunDunDM** [comment]
related [tikv#10099](https://github.com/tikv/tikv/pull/10099)

**Review by HunDunDM — APPROVED** [review]

**Review by nolouch — APPROVED** [review]

**Review by disksing — APPROVED** [review]

**Pull request merged**
