### PR TITLE
election: fix the etcd transaction failure that may be triggered during PD leader campaign

### LINKED ISSUE #3849: Deleting PD leader key meets error after kill and reboot the pd-server
## Bug Report

<!-- Please answer these questions before submitting your issue. Thanks! -->

### What did you do?

First, run a pd-server locally.

```shell
./bin/pd-server --name="pd" \                                                                                                                                                                                                                                                                                       
                --data-dir="pd" \
                --client-urls="http://127.0.0.1:2379" \
                --peer-urls="http://127.0.0.1:2380" \
                --log-file=pd.log
```

After killing it by `kill -9`, reboot the pd-server again.

```shell
./bin/pd-server --name="pd" \                                                                                                                                                                                                                                                                                       
                --data-dir="pd" \
                --client-urls="http://127.0.0.1:2379" \
                --peer-urls="http://127.0.0.1:2380" \
                --log-file=pd.log
```

### What did you expect to see?

This local PD server deletes its own leader key and campaign again immediately.

### What did you see instead?

The error message keeps showing `[PD:etcd:ErrEtcdTxnConflict]etcd transaction failed, conflicted and rolled back`, which lasts for about 10 seconds, after that the PD leader campaign successfully.

```shell
[2021/07/08 23:51:08.317 +08:00] [WARN] [member.go:174] ["the pd leader has not changed, delete and campaign again"] [old-pd-leader="name:\"pd\" member_id:3474484975246189105 peer_urls:\"http://127.0.0.1:2380\" client_urls:\"http://127.0.0.1:2379\" "]
[2021/07/08 23:51:08.317 +08:00] [ERROR] [member.go:176] ["deleting pd leader key meets error"] [error="[PD:etcd:ErrEtcdTxnConflict]etcd transaction failed, conflicted and rolled back"]
[2021/07/08 23:51:08.519 +08:00] [WARN] [member.go:174] ["the pd leader has not changed, delete and campaign again"] [old-pd-leader="name:\"pd\" member_id:3474484975246189105 peer_urls:\"http://127.0.0.1:2380\" client_urls:\"http://127.0.0.1:2379\" "]
[2021/07/08 23:51:08.520 +08:00] [ERROR] [member.go:176] ["deleting pd leader key meets error"] [error="[PD:etcd:ErrEtcdTxnConflict]etcd transaction failed, conflicted and rolled back"]
[2021/07/08 23:51:08.721 +08:00] [WARN] [member.go:174] ["the pd leader has not changed, delete and campaign again"] [old-pd-leader="name:\"pd\" member_id:3474484975246189105 peer_urls:\"http://127.0.0.1:2380\" client_urls:\"http://127.0.0.1:2379\" "]
[2021/07/08 23:51:08.721 +08:00] [ERROR] [member.go:176] ["deleting pd leader key meets error"] [error="[PD:etcd:ErrEtcdTxnConflict]etcd transaction failed, conflicted and rolled back"]
[2021/07/08 23:51:08.922 +08:00] [WARN] [member.go:174] ["the pd leader has not changed, delete and campaign again"] [old-pd-leader="name:\"pd\" member_id:3474484975246189105 peer_urls:\"http://127.0.0.1:2380\" client_urls:\"http://127.0.0.1:2379\" "]
[2021/07/08 23:51:08.924 +08:00] [ERROR] [member.go:176] ["deleting pd leader key meets error"] [error="[PD:etcd:ErrEtcdTxnConflict]etcd transaction failed, conflicted and rolled back"]
[2021/07/08 23:51:09.125 +08:00] [WARN] [member.go:174] ["the pd leader has not changed, delete and campaign again"] [old-pd-leader="name:\"pd\" member_id:3474484975246189105 peer_urls:\"http://127.0.0.1:2380\" client_urls:\"http://127.0.0.1:2379\" "]
[2021/07/08 23:51:09.126 +08:00] [ERROR] [member.go:176] ["deleting pd leader key meets error"] [error="[PD:etcd:ErrEtcdTxnConflict]etcd transaction failed, conflicted and rolled back"]
[2021/07/08 23:51:09.328 +08:00] [WARN] [member.go:174] ["the pd leader has not changed, delete and campaign again"] [old-pd-leader="name:\"pd\" member_id:3474484975246189105 peer_urls:\"http://127.0.0.1:2380\" client_urls:\"http://127.0.0.1:2379\" "]
[2021/07/08 23:51:09.328 +08:00] [ERROR] [member.go:176] ["deleting pd leader key meets error"] [error="[PD:etcd:ErrEtcdTxnConflict]etcd transaction failed, conflicted and rolled back"]
[2021/07/08 23:51:09.529 +08:00] [WARN] [member.go:174] ["the pd leader has not changed, delete and campaign again"] [old-pd-leader="name:\"pd\" member_id:3474484975246189105 peer_urls:\"http://127.0.0.1:2380\" client_urls:\"http://127.0.0.1:2379\" "]
[2021/07/08 23:51:09.530 +08:00] [ERROR] [member.go:176] ["deleting pd leader key meets error"] [error="[PD:etcd:ErrEtcdTxnConflict]etcd transaction failed, conflicted and rolled back"]
[2021/07/08 23:51:09.731 +08:00] [WARN] [member.go:174] ["the pd leader has not changed, delete and campaign again"] [old-pd-leader="name:\"pd\" member_id:3474484975246189105 peer_urls:\"http://127.0.0.1:2380\" client_urls:\"http://127.0.0.1:2379\" "]
[2021/07/08 23:51:09.732 +08:00] [ERROR] [member.go:176] ["deleting pd leader key meets error"] [error="[PD:etcd:ErrEtcdTxnConflict]etcd transaction failed, conflicted and rolled back"]
[2021/07/08 23:51:09.933 +08:00] [WARN] [member.go:174] ["the pd leader has not changed, delete and campaign again"] [old-pd-leader="name:\"pd\" member_id:3474484975246189105 peer_urls:\"http://127.0.0.1:2380\" client_urls:\"http://127.0.0.1:2379\" "]
[2021/07/08 23:51:09.934 +08:00] [ERROR] [member.go:176] ["deleting pd leader key meets error"] [error="[PD:etcd:ErrEtcdTxnConflict]etcd transaction failed, conflicted and rolled back"]
[2021/07/08 23:51:10.136 +08:00] [WARN] [member.go:174] ["the pd leader has not changed, delete and campaign again"] [old-pd-leader="name:\"pd\" member_id:3474484975246189105 peer_urls:\"http://127.0.0.1:2380\" client_urls:\"http://127.0.0.1:2379\" "]
[2021/07/08 23:51:10.137 +08:00] [ERROR] [member.go:176] ["deleting pd leader key meets error"] [error="[PD:etcd:ErrEtcdTxnConflict]etcd transaction failed, conflicted and rolled back"]
...
```

### What version of PD are you using (`pd-server -V`)?

![image](https://user-images.githubusercontent.com/1446531/124954384-93fc8880-e048-11eb-86a8-f3b519f96b9b.png)

### PR DESCRIPTION
**Pull request by JmPotato**
Signed-off-by: JmPotato <ghzpotato@gmail.com>

### What problem does this PR solve?

Close #3849.

### What is changed and how it works?

Delete the leader key directly rather than checking the leader value first. `LeaderTxn` will make this etcd transaction check `ls.leaderValue` before doing the deleting work, however, the current PD is not a leader yet so its `ls.leaderValue` will always be empty which will cause the etcd transaction to fail and PD will not campaign a new leader until the lease of previous leader key become expired.

https://github.com/tikv/pd/blob/c1f312845ca929242b0967ef76d799f38cb3e261/server/election/leadership.go#L134-L143

### Check List

Tests

- Manual test (add detailed scripts or steps below)

Repeat the #3849. Now the re-campaigning will happen smoothly.

```shell
[2021/07/09 01:18:42.336 +08:00] [WARN] [member.go:174] ["the pd leader has not changed, delete and campaign again"] [old-pd-leader="name:\"pd\" member_id:3474484975246189105 peer_urls:\"http://127.0.0.1:2380\" client_urls:\"http://127.0.0.1:2379\" "]
[2021/07/09 01:18:42.337 +08:00] [INFO] [server.go:1197] ["start to campaign pd leader"] [campaign-pd-leader-name=pd]
[2021/07/09 01:18:42.341 +08:00] [INFO] [lease.go:60] ["lease granted"] [lease-id=2463885191939534603] [lease-timeout=3] [purpose="pd leader election"]
[2021/07/09 01:18:42.346 +08:00] [INFO] [leadership.go:111] ["check campaign resp"] [resp="{\"header\":{\"cluster_id\":15674009460217235928,\"member_id\":3474484975246189105,\"revision\":21,\"raft_term\":3},\"succeeded\":true,\"responses\":[{\"Response\":{\"ResponsePut\":{\"header\":{\"revision\":21}}}}]}"]
[2021/07/09 01:18:42.350 +08:00] [INFO] [leadership.go:120] ["write leaderData to leaderPath ok"] [leaderPath=/pd/6982606201821179194/leader] [purpose="pd leader election"]
[2021/07/09 01:18:42.350 +08:00] [INFO] [server.go:1223] ["campaign pd leader ok"] [campaign-pd-leader-name=pd]
```

### Release note

```release-note
None.
```

### CODE REVIEW

**Review by disksing — APPROVED** [review]

**Review by HunDunDM — COMMENTED** [review]
Can you add a unit test for this?

**Comment by JmPotato** [comment]
> Can you add a unit test for this?

It seems that it's not easy to mock this situation according to the unit or integration test.

**Review by rleungx — APPROVED** [review]

**Comment by nolouch** [comment]
Do we need to pick this PR for the branches?

**Comment by JmPotato** [comment]
> Do we need to pick this PR for the branches?

I think it's not a quite critical problem, but cherry-picking is OK to me. What do you think?

**Comment by nolouch** [comment]
ok, I think it's no need.

**Pull request merged**
