### PR TITLE
resource_manager: fix unstable test TestSkipConsumptionForBackgroundJobs

### LINKED ISSUE #7129: TestSkipConsumptionForBackgroundJobs is unstable
### Which jobs are failing
```
2023-09-21T09:14:44.5603252Z --- FAIL: TestResourceManagerClientTestSuite (65.28s)
2023-09-21T09:14:44.5603629Z     --- PASS: TestResourceManagerClientTestSuite/TestAcquireTokenBucket (5.19s)
2023-09-21T09:14:44.5604018Z     --- PASS: TestResourceManagerClientTestSuite/TestBasicResourceGroupCURD (16.75s)
2023-09-21T09:14:44.5604386Z     --- PASS: TestResourceManagerClientTestSuite/TestLoadRequestUnitConfig (0.01s)
2023-09-21T09:14:44.5604767Z     --- PASS: TestResourceManagerClientTestSuite/TestRemoveStaleResourceGroup (1.13s)
2023-09-21T09:14:44.5605148Z     --- PASS: TestResourceManagerClientTestSuite/TestResourceGroupController (9.75s)
2023-09-21T09:14:44.5605597Z     --- PASS: TestResourceManagerClientTestSuite/TestResourceGroupControllerConfigChanged (2.58s)
2023-09-21T09:14:44.5606016Z     --- PASS: TestResourceManagerClientTestSuite/TestResourceManagerClientDegradedMode (2.63s)
2023-09-21T09:14:44.5606766Z     --- PASS: TestResourceManagerClientTestSuite/TestResourceManagerClientFailover (4.43s)
2023-09-21T09:14:44.5607323Z     --- PASS: TestResourceManagerClientTestSuite/TestResourcePenalty (0.05s)
2023-09-21T09:14:44.5607763Z     --- FAIL: TestResourceManagerClientTestSuite/TestSkipConsumptionForBackgroundJobs (0.16s)
2023-09-21T09:14:44.5608100Z     --- PASS: TestResourceManagerClientTestSuite/TestSwitchBurst (11.36s)
2023-09-21T09:14:44.5608456Z     --- PASS: TestResourceManagerClientTestSuite/TestWatchResourceGroup (2.40s)
```

### CI link
https://github.com/tikv/pd/actions/runs/6259625207/job/16996015136

### PR DESCRIPTION
**Pull request by HuSharp**
### What problem does this PR solve?

Issue Number: Close #7129

### What is changed and how does it work?

```commit-message
```

### Check List

Tests

- Unit test
- Integration test
- Manual test (add detailed scripts or steps below)
- No code

### Release note

```release-note
None.
```

### CODE REVIEW

**Review by lhy1024 — APPROVED** [review]

**Comment by HuSharp** [comment]
@lhy1024 can you rerun pr and leave a merge label? :) thx!
ci test because of `dashboard failed`, i will investigate it.

**Pull request merged**
