### PR TITLE
grpc-service: Add splitAndScatterRegions

### PR DESCRIPTION
**Pull request by hzh0425**
ref: https://github.com/pingcap/tidb/issues/29034

Add a method splitAndScatterRegions in grpc-service
let pd handle split and scatter regions

### CODE REVIEW

**Comment by rleungx** [comment]
Does this PR have any context?

**Comment by hzh0425** [comment]
> Does this PR have any context?

yep, this is a talent challenge program, see here : https://github.com/tikv/pd/issues/4095
my mentor is @Yisaer

**Comment by nolouch** [comment]
Also need to update the context in this issue, and do you have detail design RFC?

**Comment by hzh0425** [comment]
close #4224

**Comment by Yisaer** [comment]
> I know it's a subtask, But the design is different from the issue. Such as [pingcap/tidb#25281](https://github.com/pingcap/tidb/issues/25281), the first thing is to write the design RFC. we recommend writing proposal RFC before coding, for this topic you can discuss it at https://internals.tidb.io/t/topic/399.

Currently this task is target to merge `split` and `scatter` in PD and allow tidb to directly call this merged function. I think it only needs to use `Issue` to track this task in TiDB repo instead of rfc. This task isn't complex enough to propose a rfc.

**Comment by hzh0425** [comment]
ref: https://github.com/pingcap/tidb/issues/29034

**Pull request closed without merging**
