### PR TITLE
mcs: add a switch to dynamically enable scheduling service

### PR DESCRIPTION
**Pull request by rleungx**
### What problem does this PR solve?

Issue Number: Ref #5839.

### What is changed and how does it work?

This PR adds a switch to dynamically enable scheduling service. If we only upgrade the scheduling service, the logic could be different from the logic inside the api service. To avoid the changes of different logic bringing some troubles, we use a config to let the users control it by themselves.

```commit-message
```

### Check List

Tests

- Unit test

### Release note

```release-note
None.
```

### CODE REVIEW

**Review by CabinfeverB — APPROVED** [review]
LGTM. But I think there's a little bit of learning cost to using this configuration

**Comment by CabinfeverB** [comment]
I test it by pd-ctl 

Before
image

> config set enable-dynamic-switch "false"

After 
image

**Review by nolouch — APPROVED** [review]

**Comment by rleungx** [comment]
change to `enable-scheduling-fallback`

**Review by CabinfeverB — APPROVED** [review]

**Pull request merged**
