### PR TITLE
api: fix resign myself error

### PR DESCRIPTION
**Pull request by rickif**
### What problem does this PR solve?

This PR is to solve #3517.

### What is changed and how it works?

There's no need to resign member when only one member left in etcd cluster, therefore the `ResignEtcdLeader()` should just return in this scenario.

### Check List

Tests

- Unit test
- Integration test
- Manual test (add detailed scripts or steps below)
Origin:  
image
Fixed:
image

### Release note

- No release note

### CODE REVIEW

**Comment by rickif** [comment]
@nolouch @rleungx PTAL

**Review by disksing — APPROVED** [review]

**Comment by JmPotato** [comment]
@nolouch Should we change the "The transfer command is submitted." to "The resign command is submitted." here?

**Comment by rickif** [comment]
> @nolouch Should we change the "The transfer command is submitted." to "The resign command is submitted." here?

@JmPotato Good idea. The response has been updated.

**Comment by rickif** [comment]
@Yisaer PTAL

**Comment by JmPotato** [comment]
@rickif Actually, I'm wondering that why we should use the "transfer" semantic here. Though resigning the only one PD will cause the unavailability of the whole cluster, it's reasonable to resign a PD leader without transferring it.

**Comment by rickif** [comment]
> @rickif Actually, I'm wondering that why we should use the "transfer" semantic here. Though resigning the only one PD will cause the unavailability of the whole cluster, it's reasonable to resign a PD leader without transferring it.

https://github.com/etcd-io/etcd/blob/57a092b45d0eae6c9e600e62513ffcd2f1f25a92/raft/raft.go#L1349

Based on the etcd impliment, resigning the only one PD would do nothing and never cause the unavailability. Maybe is it better that the "regisn" behaves the same as the "transfer" ?  Namely, let the etcd handle this scenario. @JmPotato

**Review by JmPotato — APPROVED** [review]

**Pull request merged**
