### PR TITLE
*: move key_path.go

### PR DESCRIPTION
**Pull request by okJiang**
### What problem does this PR solve?

The place that access the keypath is not required to import endpoint.

Issue Number: Ref #4399

### What is changed and how does it work?

```commit-message
```

### Check List

Tests

- Unit test
- Integration test

### Release note

```release-note
None.
```

### CODE REVIEW

**Comment by lhy1024** [comment]
Maybe we will replace etcd with other backend, I don't think it is a good idea to move keypath to etcdutil.

**Comment by okJiang** [comment]
> Maybe we will replace etcd with other backend, I don't think it is a good idea to move keypath to etcdutil.

Do you have any better suggestion? In current situation, I think it is ok to move into etcdutil.

**Comment by okJiang** [comment]
> > Maybe we will replace etcd with other backend, I don't think it is a good idea to move keypath to etcdutil.
> 
> Do you have any better suggestion? In current situation, I think it is ok to move into etcdutil.

How about `utils/keypath`?

**Review by lhy1024 — COMMENTED** [review]
I think utils/keypath might be better, and see what others suggest.

**Comment by okJiang** [comment]
> I think utils/keypath might be better, and see what others suggest.

What do you think? @rleungx @JmPotato

**Comment by rleungx** [comment]
utils/keypath LGTM

**Review by rleungx — APPROVED** [review]

**Review by JmPotato — APPROVED** [review]

**Review by lhy1024 — APPROVED** [review]

**Pull request merged**
