### PR TITLE
cluster: check if region is valid before handling it (#3041)

### PR DESCRIPTION
**Pull request by ti-srebot**
cherry-pick #3041 to release-4.0

---

### What problem does this PR solve?

Currently, we first handle the region heartbeat then check if the region is valid.

### What is changed and how it works?

This PR moves the check logic to `RegionHeartbeat`

### Check List

Tests

- Unit test

### CODE REVIEW

**Comment by lhy1024** [comment]
plz fix conflict

**Comment by nolouch** [comment]
@rleungx plz fix conflict.

**Comment by nolouch** [comment]
LGTM

**Review by lhy1024 — APPROVED** [review]

**Pull request merged**
