### PR TITLE
election: add some logs

### PR DESCRIPTION
**Pull request by disksing**
Signed-off-by: disksing <i@disksing.com>

Add some logs about lease state.

### Release note 

- No release note

### CODE REVIEW

**Comment by disksing** [comment]
No release note.

**Review by JmPotato — APPROVED** [review]
LGTM

**Comment by howardlau1999** [comment]
LGTM

**Review by lhy1024 — APPROVED** [review]

**Review by JmPotato — APPROVED** [review]

**Review by Yisaer — APPROVED** [review]

**Pull request merged**
