### PR TITLE
dashboard: update hotfix version

### LINKED ISSUE #7302: Login tidb-dashboard failed in 7.1.2
## Bug Report

Login tidb-dashboard failed in cloud environment 

Error log:

```
{"error":true,"message":"authenticate failed, caused by: illegal base64 data at input byte 8","code":"api.user.signin.other","full_text":""}
```

### PR DESCRIPTION
**Pull request by mornyx**
### What problem does this PR solve?

Issue Number: Close #7302

### What is changed and how does it work?

update dashboard version to revert https://github.com/pingcap/tidb-dashboard/pull/1583 and https://github.com/pingcap/tidb-dashboard/pull/1587

### Check List

Tests

- Unit test
- Integration test
- Manual test (add detailed scripts or steps below)
- No code

Code changes

- Has the configuration change
- Has HTTP API interfaces changed (Don't forget to [add the declarative for the new API](https://github.com/tikv/pd/blob/master/docs/development.md#updating-api-documentation))
- Has persistent data change

Side effects

- Possible performance regression
- Increased code complexity
- Breaking backward compatibility

Related changes

- PR to update [`pingcap/docs`](https://github.com/pingcap/docs)/[`pingcap/docs-cn`](https://github.com/pingcap/docs-cn):
- PR to update [`pingcap/tiup`](https://github.com/pingcap/tiup):
- Need to cherry-pick to the release branch

### Release note

```release-note
None.
```

### CODE REVIEW

**Comment by baurine** [comment]
TiDB Dashboard side PR: https://github.com/pingcap/tidb-dashboard/pull/1609

**Review by rleungx — APPROVED** [review]

**Review by nolouch — APPROVED** [review]

**Pull request merged**
