### PR TITLE
*: clean up useless parameters

### PR DESCRIPTION
**Pull request by JmPotato**
Signed-off-by: JmPotato <ghzpotato@gmail.com>

### What problem does this PR solve?

Clean up useless parameters that are detected by:

```shell
golangci-lint run -E unparam
```

### What is changed and how it works?

Clean up useless parameters.

### Check List

Tests

- Unit test
- Integration test

### CODE REVIEW

**Comment by JmPotato** [comment]
> How about adding the lint to CI?

Actually, not all errors this linter reports need to be fixed.

image

Some variables are unused but still meaningful to exist.

**Review by rleungx — APPROVED** [review]

**Review by Yisaer — APPROVED** [review]

**Comment by nolouch** [comment]
Can we fix the sonar?

**Pull request merged**
