### PR TITLE
*: upgrade go from 1.19 to 1.20

### PR DESCRIPTION
**Pull request by nolouch**
### What problem does this PR solve?

Issue Number: Close https://github.com/tikv/pd/issues/6029

### What is changed and how does it work?

```commit-message
*: upgrade go from 1.19 to 1.20
```

### Check List

Tests

- Unit test
- Integration test

### Release note

```release-note
None.
```

### CODE REVIEW

**Review by rleungx — APPROVED** [review]

**Review by lhy1024 — APPROVED** [review]

**Comment by lhy1024** [comment]
ci failed

**Comment by nolouch** [comment]
wait https://github.com/PingCAP-QE/ci/pull/1821 @purelind

**Comment by purelind** [comment]
> wait [PingCAP-QE/ci#1821](https://github.com/PingCAP-QE/ci/pull/1821) @purelind

https://github.com/PingCAP-QE/ci/pull/1821 has been merged.

**Pull request merged**
