### PR TITLE
test: fix unstable test TestClientWatchWithRevision

### LINKED ISSUE #6013: TestClientWatchWithRevision is unstable
### Which jobs are failing

TestGlobalConfigTestSuite 
### Reason for failure (if possible)
```
 --- FAIL: TestGlobalConfigTestSuite (5.14s)
2023-02-17T03:13:58.0444036Z     --- FAIL: TestGlobalConfigTestSuite/TestClientWatchWithRevision (1.06s)
2023-02-17T03:13:58.0444283Z         global_config_test.go:293: 
2023-02-17T03:13:58.0444834Z             	Error Trace:	/home/runner/work/pd/pd/tests/client/global_config_test.go:293
2023-02-17T03:13:58.0445131Z             	Error:      	Not equal: 
2023-02-17T03:13:58.0445435Z             	            	expected: 28
2023-02-17T03:13:58.0445729Z             	            	actual  : 29
2023-02-17T03:13:58.0446939Z             	Test:       	TestGlobalConfigTestSuite/TestClientWatchWithRevision
2023-02-17T03:13:58.0447022Z FAIL
2023-02-17T03:13:58.0447545Z [2023/02/17 03:13:56.633 +00:00] [WARN] [grpclog.go:60] ["grpc: addrConn.createTransport failed to connect to {127.0.0.1:46139  <nil> 0 <nil>}. Err :connection error: desc = \"transport: Error while dialing dial tcp 127.0.0.1:46139: connect: connection refused\". Reconnecting..."]
```

### PR DESCRIPTION
**Pull request by glorv**
### What problem does this PR solve?

Issue Number: Close #6013

### What is changed and how does it work?

```
```

### Check List

Tests

- Unit test

Code changes

Side effects

Related changes

- PR to update [`pingcap/docs`](https://github.com/pingcap/docs)/[`pingcap/docs-cn`](https://github.com/pingcap/docs-cn):
- PR to update [`pingcap/tiup`](https://github.com/pingcap/tiup):
- Need to cherry-pick to the release branch

### Release note

```release-note
None.
```

### CODE REVIEW

**Comment by glorv** [comment]
@HuSharp  @rleungx PTAL

**Review by rleungx — APPROVED** [review]

**Review by HuSharp — APPROVED** [review]

**Review by lhy1024 — APPROVED** [review]

**Comment by lhy1024** [comment]
ci failed

**Comment by glorv** [comment]
> ci failed

```
2023-02-28T03:16:32.9177308Z panic: test timed out after 15m0s
2023-02-28T03:16:32.9177411Z running tests:
2023-02-28T03:16:32.9177590Z    TestTSOServerStartAndStopNormally (15m0s)
2023-02-28T03:16:32.9177601Z
2023-02-28T03:16:32.9177713Z goroutine 1270655 [running]:
2023-02-28T03:16:32.9177836Z testing.(*M).startAlarm.func1()
2023-02-28T03:16:32.9178048Z    /opt/hostedtoolcache/go/1.20.1/x64/src/testing/testing.go:2241 +0x219
2023-02-28T03:16:32.9178156Z created by time.goFunc
2023-02-28T03:16:32.9178352Z    /opt/hostedtoolcache/go/1.20.1/x64/src/time/sleep.go:176 +0x48
2023-02-28T03:16:32.9178361Z
2023-02-28T03:16:32.9178487Z goroutine 1 [chan receive, 15 minutes]:
2023-02-28T03:16:32.9178642Z testing.(*T).Run(0xc000380b60, {0x3ed7c92, 0x21}, 0x4954e70)
2023-02-28T03:16:32.9178851Z    /opt/hostedtoolcache/go/1.20.1/x64/src/testing/testing.go:1630 +0x82e
2023-02-28T03:16:32.9178975Z testing.runTests.func1(0x0?)
2023-02-28T03:16:32.9179164Z    /opt/hostedtoolcache/go/1.20.1/x64/src/testing/testing.go:2036 +0x8e
2023-02-28T03:16:32.9179302Z testing.tRunner(0xc000380b60, 0xc0003cdb40)
2023-02-28T03:16:32.9179601Z    /opt/hostedtoolcache/go/1.20.1/x64/src/testing/testing.go:1576 +0x217
2023-02-28T03:16:32.9179786Z testing.runTests(0xc0006b0140?, {0x659be10, 0x1, 0x1}, {0x1c?, 0x1e?, 0x6695b00?})
2023-02-28T03:16:32.9179990Z    /opt/hostedtoolcache/go/1.20.1/x64/src/testing/testing.go:2034 +0x87d
2023-02-28T03:16:32.9180103Z testing.(*M).Run(0xc0006b0140)
2023-02-28T03:16:32.9180301Z    /opt/hostedtoolcache/go/1.20.1/x64/src/testing/testing.go:1906 +0xb45
2023-02-28T03:16:32.9180395Z main.main()
2023-02-28T03:16:32.9180512Z    _testmain.go:78 +0x2fd
```
Another unstable test😂

**Pull request merged**
